"use client"
import { useEffect, useRef, useState } from "react"
import { Loader2, Pencil, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"
import { Sheet,SheetContent,SheetDescription,SheetFooter,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { useToast } from "@/hooks/use-toast"
import type { ActorKind } from "@/lib/actors"

export type ActorRecord=Record<string,string>
const labels:Record<ActorKind,string>={athletes:"athlète",coachs:"coach",officiels:"officiel",arbitres:"arbitre",medecins:"médecin",autres:"autre acteur"}
const fields=[
  ["nom_complet","Nom complet","text","Identification"],["id_sexe","Sexe","sex","Identification"],["date_de_naissance","Date de naissance","date","Identification"],["lieu_de_naissance","Lieu de naissance","text","Identification"],["nationalite","Nationalité","text","Identification"],["id_national","Identifiant national","text","Identification"],["id_international","Identifiant international","text","Identification"],["statut","Statut","status","Identification"],
  ["telephone","Téléphone","tel","Coordonnées"],["email","Courriel","email","Coordonnées"],["adresse","Adresse","text","Coordonnées"],
  ["numero_passeport","Numéro de passeport","text","Passeport"],["date_de_delivrance_passeport","Date de délivrance","date","Passeport"],["date_expiration_passeport","Date d’expiration","date","Passeport"],
  ["observations","Observations","textarea","Complément"],
] as const
const initial=(actor?:ActorRecord)=>Object.fromEntries(fields.map(([key])=>[key,actor?.[key]??""]).concat([["id_specialite_sante",actor?.id_specialite_sante??""],["id_type_autre_acteur",actor?.id_type_autre_acteur??""]]))

export function ActorEditor({kind,actor,onSaved,buttonLabel}:{kind:ActorKind;actor?:ActorRecord;onSaved?:(actor:ActorRecord)=>void;buttonLabel?:string}){
  const {toast}=useToast(), submitting=useRef(false)
  const [federal,setFederal]=useState(false),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[values,setValues]=useState<Record<string,string>>(()=>initial(actor)),[errors,setErrors]=useState<Record<string,string>>({}),[refs,setRefs]=useState<Record<string,{id:string;label:string}[]>>({})
  useEffect(()=>{void fetch("/api/auth/me").then(r=>r.json()).then(j=>setFederal(j?.user?.role==="federal"))},[])
  if(!federal)return null
  const set=(key:string,value:string)=>setValues(v=>({...v,[key]:value}))
  const start=async()=>{setValues(initial(actor));setErrors({});setOpen(true);try{const r=await fetch("/api/acteurs/referentiels",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Référentiels indisponibles.");setRefs(j.referentiels||{});if(kind==="medecins"&&!j.referentiels?.SPECIALITES_MEDECINS?.length)setErrors({_form:"Anomalie : le référentiel SPECIALITES_MEDECINS est vide."})}catch(e){setErrors({_form:e instanceof Error?e.message:"Référentiels indisponibles."})}}
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(submitting.current)return;submitting.current=true;setSaving(true);setErrors({});try{const endpoint=`/api/${kind}${actor?`/${encodeURIComponent(actor.id)}`:""}`,r=await fetch(endpoint,{method:actor?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)}),j=await r.json();if(!r.ok){setErrors({...j?.error?.fields,_form:j?.error?.message||"Enregistrement impossible."});return}onSaved?.(j.actor);setOpen(false);toast({title:actor?"Modification enregistrée":"Création enregistrée",description:`La fiche ${labels[kind]} a été enregistrée.`})}catch{setErrors({_form:"Service temporairement indisponible."})}finally{submitting.current=false;setSaving(false)}}
  const renderField=([key,label,type]:typeof fields[number])=>{const id=`actor-${kind}-${key}`,error=errors[key];if(type==="sex"||type==="status"){const options=type==="sex"?(refs.SEXES||[]):[{id:"ACTIF",label:"Actif"},{id:"INACTIF",label:"Inactif"}];return <div key={key} className="space-y-2"><Label htmlFor={id}>{label} *</Label><Select value={values[key]} onValueChange={v=>set(key,v)} disabled={saving}><SelectTrigger id={id} aria-invalid={!!error}><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.label}</SelectItem>)}</SelectContent></Select>{error?<p className="text-sm text-destructive">{error}</p>:null}</div>};return <div key={key} className={type==="textarea"?"space-y-2 md:col-span-2":"space-y-2"}><Label htmlFor={id}>{label}{key==="nom_complet"?" *":""}</Label>{type==="textarea"?<Textarea id={id} value={values[key]} onChange={e=>set(key,e.target.value)} disabled={saving}/>:<Input id={id} type={type} value={values[key]} onChange={e=>set(key,e.target.value)} disabled={saving} aria-invalid={!!error}/>} {error?<p className="text-sm text-destructive">{error}</p>:null}</div>}
  const extra=kind==="medecins"?["id_specialite_sante","Spécialité","SPECIALITES_MEDECINS"]:kind==="autres"?["id_type_autre_acteur","Type d’autre acteur","TYPES_AUTRES_ACTEURS"]:null
  return <><Button type="button" variant={actor?"outline":"default"} onClick={()=>void start()}>{actor?<Pencil/>:<Plus/>}{buttonLabel??(actor?"Modifier":`Ajouter un ${labels[kind]}`)}</Button><Sheet open={open} onOpenChange={v=>{if(!saving)setOpen(v)}}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{actor?"Modifier": "Ajouter"} {labels[kind]}</SheetTitle><SheetDescription>Identité et informations stables uniquement. L’identifiant principal est généré par le serveur.</SheetDescription></SheetHeader><form onSubmit={submit} className="space-y-6 px-4 pb-6"><div className="rounded-lg bg-muted/50 p-3 text-sm"><span className="font-medium">Identifiant principal : </span>{actor?.id||"Attribué à la création"}</div>{["Identification","Coordonnées","Passeport","Complément"].map(section=><fieldset key={section} className="grid gap-4 md:grid-cols-2"><legend className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground md:col-span-2">{section}</legend>{fields.filter(f=>f[3]===section).map(renderField)}{section==="Complément"&&extra?<div className="space-y-2"><Label>{extra[1]}</Label><Select value={values[extra[0]]} onValueChange={v=>set(extra[0],v)} disabled={saving}><SelectTrigger aria-invalid={!!errors[extra[0]]}><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{(refs[extra[2]]||[]).map(o=><SelectItem key={o.id} value={o.id}>{o.label}</SelectItem>)}</SelectContent></Select>{errors[extra[0]]?<p className="text-sm text-destructive">{errors[extra[0]]}</p>:null}</div>:null}</fieldset>)}{errors._form?<p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{errors._form}</p>:null}<SheetFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)} disabled={saving}>Annuler</Button><Button type="submit" disabled={saving}>{saving?<><Loader2 className="animate-spin"/>Enregistrement…</>:"Enregistrer"}</Button></SheetFooter></form></SheetContent></Sheet></>
}
