"use client";

import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Check, Flag, Loader2, Plus, Search, Stethoscope, UserRound, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Person = { id: string; nom: string; role: string; club: string; equipe: string; detail: string };
type Category = "athletes" | "arbitres" | "officiels" | "medecins" | "autres";
type Candidate = Person & { teamId?: string; clubId?: string };
type Payload = Record<Category, Person[]> & { available: Record<Category, Candidate[]>; limitations?: Partial<Record<Category, string>> };
const categories: Array<{ key: Category; label: string; icon: typeof Users }> = [
  { key: "athletes", label: "Athlètes", icon: UserRound }, { key: "arbitres", label: "Arbitres", icon: Flag },
  { key: "officiels", label: "Officiels", icon: BadgeCheck }, { key: "medecins", label: "Médecins", icon: Stethoscope },
  { key: "autres", label: "Autres", icon: Users },
];
const empty: Payload = { athletes: [], arbitres: [], officiels: [], medecins: [], autres: [], available: { athletes: [], arbitres: [], officiels: [], medecins: [], autres: [] } };

export function CompetitionPeoplePanel({ competitionId, readOnly=false }: { competitionId: string; readOnly?: boolean }) {
  const [data, setData] = useState<Payload>(empty), [category, setCategory] = useState<Category>("athletes"), [query, setQuery] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [federal, setFederal] = useState(false);
  const [adding, setAdding] = useState(false), [candidateQuery, setCandidateQuery] = useState(""), [selectedId, setSelectedId] = useState(""), [role, setRole] = useState("");
  useEffect(() => { let active = true; void fetch(`/api/competitions/${encodeURIComponent(competitionId)}/people`, { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.error || "Lecture impossible."); if (active) setData(payload); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Lecture impossible."); }).finally(() => { if (active) setLoading(false); }); void fetch("/api/auth/me").then((response) => response.json()).then((payload) => { if (active) setFederal(!readOnly && payload?.user?.role === "federal"); }); return () => { active = false; }; }, [competitionId,readOnly]);
  const people = useMemo(() => data[category].filter((person) => Object.values(person).join(" ").toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr"))), [category, data, query]);
  const candidates = useMemo(() => { const needle = candidateQuery.trim().toLocaleLowerCase("fr"); if (!needle) return []; return data.available[category].filter((person) => `${person.id} ${person.nom} ${person.club} ${person.equipe} ${person.role}`.toLocaleLowerCase("fr").includes(needle)).slice(0, 20); }, [candidateQuery, category, data.available]);
  const selected = data.available[category].find((person) => person.id === selectedId);
  const add = async () => { if (!selectedId || (category === "officiels" && !role.trim())) return; setAdding(true); setError(""); try { const response = await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/people`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, actorId: selectedId, role }) }), payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || "Enregistrement impossible."); setData(payload); setCandidateQuery(""); setSelectedId(""); setRole(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setAdding(false); } };
  if (loading) return <p className="py-8 text-center text-muted-foreground"><Loader2 className="mr-2 inline size-4 animate-spin"/>Chargement des participants…</p>;
  return <section className="space-y-5">
    <div><h2 className="text-lg font-semibold">Participants à la compétition</h2><p className="text-sm text-muted-foreground">Personnes rattachées aux équipes et clubs engagés, présentées selon leur fonction.</p></div>
    {error ? <p role="alert" className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</p> : null}
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{categories.map(({ key, label, icon: Icon }) => <button key={key} type="button" onClick={() => { setCategory(key); setQuery(""); setCandidateQuery(""); setSelectedId(""); setRole(""); }} className={cn("rounded-xl border p-4 text-left transition-colors", category === key ? "border-primary bg-primary/10" : "bg-card hover:bg-muted/50")}><div className="flex items-center justify-between"><Icon className={cn("size-5", category === key ? "text-primary" : "text-muted-foreground")}/><span className="text-2xl font-bold tabular-nums">{data[key].length}</span></div><p className="mt-3 text-sm font-medium">{label}</p></button>)}</div>
    {federal ? <Card className="gap-4 py-5 shadow-sm"><CardContent className="space-y-4 px-5"><div><h3 className="font-semibold">Ajouter un participant</h3><p className="text-sm text-muted-foreground">{category === "athletes" ? "Seuls les athlètes avec une affiliation active dans une équipe engagée sont proposés." : `Recherchez une personne dans le registre ${categories.find((item) => item.key === category)?.label.toLocaleLowerCase("fr")}.`}</p></div><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={candidateQuery} onChange={(event) => { setCandidateQuery(event.target.value); setSelectedId(""); }} placeholder="Saisir un nom ou un identifiant…" className="pl-9"/></div>{candidateQuery && !selectedId ? <div className="max-h-64 overflow-y-auto rounded-lg border">{candidates.length ? candidates.map((candidate) => <button key={candidate.id} type="button" onClick={() => { setSelectedId(candidate.id); setCandidateQuery(candidate.nom); }} className="flex w-full items-center gap-3 border-b p-3 text-left last:border-b-0 hover:bg-muted/50"><Initials name={candidate.nom}/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{candidate.nom}</strong><small className="block truncate text-muted-foreground">{candidate.id} · {candidate.role}{candidate.equipe !== "-" ? ` · ${candidate.equipe}` : ""}</small></span></button>) : <p className="p-4 text-center text-sm text-muted-foreground">Aucune personne disponible.</p>}</div> : null}{selected ? <div className="flex items-center gap-3 rounded-lg border border-primary/30 bg-primary/5 p-3"><Check className="size-5 text-primary"/><div className="min-w-0"><p className="font-medium">{selected.nom}</p><p className="text-xs text-muted-foreground">{selected.id} · {selected.club}{selected.equipe !== "-" ? ` · ${selected.equipe}` : ""}</p></div></div> : null}{category === "officiels" && selected ? <div className="space-y-1"><label htmlFor="competition-official-role" className="text-sm font-medium">Rôle dans cette compétition</label><Input id="competition-official-role" value={role} onChange={(event) => setRole(event.target.value)} placeholder="Ex. Commissaire de match"/></div> : null}<Button onClick={() => void add()} disabled={adding || !selectedId || (category === "officiels" && !role.trim())}>{adding ? <Loader2 className="animate-spin"/> : <Plus/>}Ajouter aux participants</Button></CardContent></Card> : null}
    <div className="relative max-w-md"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Rechercher parmi les ${categories.find((item) => item.key === category)?.label.toLocaleLowerCase("fr")}…`} className="pl-9"/></div>
    {data.limitations?.[category] ? <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">{data.limitations[category]}</p> : null}
    {people.length ? <PeopleList category={category} people={people}/> : <div className="rounded-xl border border-dashed p-10 text-center"><Users className="mx-auto size-8 text-muted-foreground/60"/><p className="mt-3 font-medium">Aucun participant dans cette catégorie</p><p className="mt-1 text-sm text-muted-foreground">Les personnes apparaîtront ici lorsqu’une relation valide avec la compétition sera disponible.</p></div>}
  </section>;
}

function PeopleList({ category, people }: { category: Category; people: Person[] }) {
  const detailLabel = category === "athletes" ? "Maillot" : category === "arbitres" ? "Grade" : category === "medecins" ? "Spécialité" : category === "officiels" ? "Affectation" : "Structure";
  return <Card className="gap-0 overflow-hidden py-0 shadow-sm"><CardContent className="p-0"><div className="hidden grid-cols-[minmax(100px,.7fr)_minmax(180px,1.4fr)_minmax(140px,1fr)_minmax(140px,1fr)_minmax(120px,.8fr)] bg-muted/35 text-xs font-semibold uppercase tracking-wide text-muted-foreground md:grid"><span className="p-3">Identifiant</span><span className="p-3">Nom</span><span className="p-3">{category === "athletes" || category === "medecins" ? "Club / équipe" : "Structure"}</span><span className="p-3">Rôle</span><span className="p-3">{detailLabel}</span></div>{people.map((person) => <div key={`${category}-${person.id}`} className="border-t first:border-t-0"><div className="hidden grid-cols-[minmax(100px,.7fr)_minmax(180px,1.4fr)_minmax(140px,1fr)_minmax(140px,1fr)_minmax(120px,.8fr)] items-center text-sm md:grid"><span className="break-all p-3 font-mono text-xs text-muted-foreground">{person.id}</span><Name person={person}/><span className="p-3"><strong className="block font-medium">{person.club}</strong>{person.equipe !== "-" ? <small className="text-muted-foreground">{person.equipe}</small> : null}</span><span className="p-3">{person.role}</span><span className="p-3 text-muted-foreground">{person.detail}</span></div><div className="p-4 md:hidden"><div className="flex items-start gap-3"><Initials name={person.nom}/><div className="min-w-0 flex-1"><p className="font-semibold">{person.nom}</p><p className="break-all font-mono text-xs text-muted-foreground">{person.id}</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Meta label="Rôle" value={person.role}/><Meta label={detailLabel} value={person.detail}/><Meta label="Club" value={person.club}/>{person.equipe !== "-" ? <Meta label="Équipe" value={person.equipe}/> : null}</div></div></div></div></div>)}</CardContent></Card>;
}

function Name({ person }: { person: Person }) { return <span className="flex min-w-0 items-center gap-3 p-3"><Initials name={person.nom}/><strong className="min-w-0 break-words font-medium">{person.nom}</strong></span>; }
function Initials({ name }: { name: string }) { return <span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</span>; }
function Meta({ label, value }: { label: string; value: string }) { return <span><small className="block text-muted-foreground">{label}</small><span className="break-words">{value}</span></span>; }
