"use client";

import { useEffect, useState } from "react";
import { Loader2, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import type { Competition } from "@/lib/models";

type Option = { id: string; label: string };
type Refs = { types: Option[]; disciplines: Option[]; seasons: Option[] };

export function CompetitionEditSheet({ competition, onUpdated }: { competition: Competition; onUpdated: (competition: Competition) => void }) {
  const [allowed, setAllowed] = useState(false), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [refs, setRefs] = useState<Refs>({ types: [], disciplines: [], seasons: [] }), [errors, setErrors] = useState<Record<string, string>>({}), [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => { void fetch("/api/auth/me").then((response) => response.json()).then((payload) => setAllowed(payload?.user?.role === "federal")); }, []);
  const initial = () => ({ nom_competition: competition.nom, id_type_competition: competition.typeCompetitionId || "", id_discipline: competition.disciplineId || "", id_saison: competition.saisonId || "", date_debut: competition.dateDebut, date_fin: competition.dateFin, pays: competition.pays, lieu: competition.lieu || "", statut: competition.statut, observations: competition.observation || "" });
  const start = () => { setValues(initial()); setErrors({}); setOpen(true); void fetch("/api/competitions/referentiels", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Référentiels indisponibles."); setRefs(payload); if (competition.saisonId && !payload.seasons.some((item: Option) => item.id === competition.saisonId)) setErrors({ id_saison: `Saison non référencée (${competition.saisonId}). Sélectionnez une saison valide.` }); }).catch((error) => setErrors({ _form: error instanceof Error ? error.message : "Référentiels indisponibles." })); };
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const select = (key: string, label: string, options: Option[]) => <div className="space-y-2"><Label>{label} *</Label><Select value={values[key]} onValueChange={(value) => set(key, value)} disabled={saving || options.length === 0}><SelectTrigger aria-invalid={!!errors[key]}><SelectValue placeholder={options.length ? "Sélectionner" : "Référentiel vide"}/></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option.id} value={option.id}>{option.label}</SelectItem>)}</SelectContent></Select>{errors[key] ? <p className="text-sm text-destructive">{errors[key]}</p> : null}</div>;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setErrors({}); try { const response = await fetch(`/api/competitions/${encodeURIComponent(competition.id)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) { setErrors({ ...(payload.error?.fields || {}), _form: payload.error?.message || "Modification impossible." }); return; } onUpdated(payload.competition); setOpen(false); } catch { setErrors({ _form: "Service temporairement indisponible." }); } finally { setSaving(false); } };
  if (!allowed) return null;
  return <><Button variant="outline" onClick={start}><Pencil/>Modifier</Button><Sheet open={open} onOpenChange={(value) => { if (!saving) setOpen(value); }}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Modifier la compétition</SheetTitle><SheetDescription>L’identifiant {competition.id} est conservé et ne peut pas être modifié.</SheetDescription></SheetHeader><form onSubmit={submit} className="space-y-5 px-4 pb-6"><div className="space-y-2"><Label>Identifiant</Label><Input value={competition.id} disabled/></div><div className="space-y-2"><Label>Nom *</Label><Input value={values.nom_competition || ""} onChange={(event) => set("nom_competition", event.target.value)} aria-invalid={!!errors.nom_competition}/>{errors.nom_competition ? <p className="text-sm text-destructive">{errors.nom_competition}</p> : null}</div><div className="grid gap-4 sm:grid-cols-2">{select("id_type_competition", "Type", refs.types)}{select("id_discipline", "Discipline", refs.disciplines)}{select("id_saison", "Saison", refs.seasons)}{select("statut", "Statut", ["PLANIFIEE", "EN_COURS", "TERMINEE", "ANNULEE"].map((id) => ({ id, label: id })))}<div className="space-y-2"><Label>Date de début *</Label><Input type="date" value={values.date_debut || ""} onChange={(event) => set("date_debut", event.target.value)} aria-invalid={!!errors.date_debut}/>{errors.date_debut ? <p className="text-sm text-destructive">{errors.date_debut}</p> : null}</div><div className="space-y-2"><Label>Date de fin *</Label><Input type="date" value={values.date_fin || ""} onChange={(event) => set("date_fin", event.target.value)} aria-invalid={!!errors.date_fin}/>{errors.date_fin ? <p className="text-sm text-destructive">{errors.date_fin}</p> : null}</div></div><div className="space-y-2"><Label>Pays *</Label><Input value={values.pays || ""} onChange={(event) => set("pays", event.target.value)} aria-invalid={!!errors.pays}/></div><div className="space-y-2"><Label>Observations</Label><Textarea value={values.observations || ""} onChange={(event) => set("observations", event.target.value)}/></div>{errors._form ? <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{errors._form}</p> : null}<SheetFooter><Button type="button" variant="outline" onClick={() => setOpen(false)} disabled={saving}>Annuler</Button><Button type="submit" disabled={saving || !refs.seasons.length}>{saving ? <><Loader2 className="animate-spin"/>Modification…</> : "Enregistrer"}</Button></SheetFooter></form></SheetContent></Sheet></>;
}
