"use client";
import { useCallback, useEffect, useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
type Event = { id: string; nom: string; statut: string };
type Phase = { id: string; eventId: string; nom: string; modeId: string; numero: string; statut: string; typeNom: string; modeNom: string; unitCount: number; matchCount: number };
type Group = { id: string; phaseId: string; nom: string }; type Ref = { id: string; nom: string };
export function CompetitionStructurePanel({ competitionId, readOnly=false }: { competitionId: string; readOnly?: boolean }) {
  const [events,setEvents]=useState<Event[]>([]),[phases,setPhases]=useState<Phase[]>([]),[groups,setGroups]=useState<Group[]>([]),[types,setTypes]=useState<Ref[]>([]),[modes,setModes]=useState<Ref[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[federal,setFederal]=useState(false),[error,setError]=useState("");
  const [eventId,setEventId]=useState(""),[phaseName,setPhaseName]=useState(""),[phaseTypeId,setPhaseTypeId]=useState(""),[phaseModeId,setPhaseModeId]=useState(""),[phaseNumber,setPhaseNumber]=useState(""),[groupName,setGroupName]=useState(""),[phaseId,setPhaseId]=useState("");
  const endpoint=`/api/competitions/${encodeURIComponent(competitionId)}/structure`;
  const apply=(d:{events?:Event[];phases?:Phase[];groups?:Group[];types?:Ref[];modes?:Ref[]})=>{setEvents(d.events||[]);setPhases(d.phases||[]);setGroups(d.groups||[]);setTypes(d.types||[]);setModes(d.modes||[])};
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(endpoint,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Lecture impossible.");apply(d)}catch(c){setError(c instanceof Error?c.message:"Lecture impossible.")}finally{setLoading(false)}},[endpoint]);
  useEffect(()=>{void load();void fetch("/api/auth/me").then(r=>r.json()).then(p=>setFederal(!readOnly&&p?.user?.role==="federal"))},[load,readOnly]);
  const create=async(kind:"phase"|"groupe")=>{setSaving(true);setError("");try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,eventId,nom:kind==="phase"?phaseName:groupName,phaseId,typeId:phaseTypeId,modeId:phaseModeId,numero:phaseNumber})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Enregistrement impossible.");const id=String(d?.created?.id||"");if(!id)throw new Error("Identifiant créé introuvable.");if(kind==="phase"){setPhases(current=>[...current,{id,eventId,nom:phaseName,modeId:phaseModeId,numero:phaseNumber,statut:"ACTIF",typeNom:types.find(x=>x.id===phaseTypeId)?.nom||phaseTypeId,modeNom:modes.find(x=>x.id===phaseModeId)?.nom||phaseModeId,unitCount:0,matchCount:0}]);setPhaseName("");setPhaseTypeId("");setPhaseModeId("");setPhaseNumber("")}else{setGroups(current=>[...current,{id,phaseId,nom:groupName}]);setGroupName("")}}catch(c){setError(c instanceof Error?c.message:"Enregistrement impossible.")}finally{setSaving(false)}};
  if(loading)return <p className="text-muted-foreground"><Loader2 className="mr-2 inline size-4 animate-spin"/>Chargement…</p>;
  return <div className="space-y-5"><p className="text-sm text-muted-foreground">Les phases sont rattachées à une épreuve. Les groupes sont réservés au mode GROUPES.</p>{error?<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-destructive/30 p-3 text-sm text-destructive"><p>{error}</p><Button type="button" variant="outline" size="sm" onClick={()=>void load()}>Réessayer</Button></div>:null}
    {federal?<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Créer une phase</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Select value={eventId} onValueChange={setEventId}><SelectTrigger className="sm:col-span-2"><SelectValue placeholder="Épreuve concernée"/></SelectTrigger><SelectContent>{events.filter(e=>e.statut!=="INACTIF").map(e=><SelectItem key={e.id} value={e.id}>{e.nom}</SelectItem>)}</SelectContent></Select><Select value={phaseTypeId} onValueChange={setPhaseTypeId}><SelectTrigger><SelectValue placeholder="Type"/></SelectTrigger><SelectContent>{types.map(x=><SelectItem key={x.id} value={x.id}>{x.nom.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select><Select value={phaseModeId} onValueChange={setPhaseModeId}><SelectTrigger><SelectValue placeholder="Mode"/></SelectTrigger><SelectContent>{modes.map(x=><SelectItem key={x.id} value={x.id}>{x.nom.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select><Input value={phaseNumber} onChange={e=>setPhaseNumber(e.target.value)} placeholder="Ordre"/><Input value={phaseName} onChange={e=>setPhaseName(e.target.value)} placeholder="Nom affiché"/><Button className="sm:col-span-2" onClick={()=>void create("phase")} disabled={saving||!eventId||!phaseTypeId||!phaseModeId||!phaseName.trim()}><Plus/>Ajouter</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Créer un groupe</CardTitle></CardHeader><CardContent className="grid gap-3"><Select value={phaseId} onValueChange={setPhaseId}><SelectTrigger><SelectValue placeholder="Phase en mode groupes"/></SelectTrigger><SelectContent>{phases.filter(p=>p.modeId==="MPH001").map(p=><SelectItem key={p.id} value={p.id}>{p.nom}</SelectItem>)}</SelectContent></Select><div className="flex gap-2"><Input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Ex. Groupe A"/><Button onClick={()=>void create("groupe")} disabled={saving||!phaseId||!groupName.trim()}><Plus/>Ajouter</Button></div></CardContent></Card></div>:null}
    {events.map(event=><section key={event.id} className="space-y-3"><h3 className="text-lg font-semibold">{event.nom}</h3><div className="grid gap-4 md:grid-cols-2">{phases.filter(p=>p.eventId===event.id).map(p=><Card key={p.id}><CardHeader><CardTitle>{p.numero?`${p.numero}. `:""}{p.nom}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{p.typeNom.replaceAll("_"," ")} · {p.modeNom.replaceAll("_"," ")} · {p.statut}</p><p className="text-sm font-medium">{p.unitCount} unité(s) · {p.matchCount} match(s)</p>{p.modeId==="MPH001"?<div className="flex flex-wrap gap-2">{groups.filter(g=>g.phaseId===p.id).map(g=><span key={g.id} className="rounded-full border px-3 py-1 text-sm">{g.nom}</span>)}{!groups.some(g=>g.phaseId===p.id)?<span className="text-sm text-amber-700">Aucun groupe configuré</span>:null}</div>:<p className="text-sm text-muted-foreground">Aucun groupe requis</p>}</CardContent></Card>)}</div></section>)}{!events.length?<p className="rounded-lg border p-5 text-center text-muted-foreground">Commencez par créer une épreuve.</p>:null}</div>;
}
