"use client";

import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Check, Flag, Loader2, Plus, Search, Stethoscope, UserRound, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatDisplayDate } from "@/lib/date-format";
import { cn } from "@/lib/utils";

type Validity = "VALIDE" | "NON_VALIDE" | "NON_APPLICABLE" | "INDETERMINE";
type Person = { id: string; nom: string; role: string; club: string; equipe: string; detail: string; grade: string; numeroLicence: string | null; statutParticipation: Validity; raisonStatutParticipation: string; dateDebutValidite: string | null; dateFinValidite: string | null; qualiteDonnees: string | null };
type Category = "athletes" | "arbitres" | "officiels" | "medecins" | "autres";
type Candidate = Person & { teamId?: string; clubId?: string; unitId?: string; selectionId: string };
type Payload = Record<Category, Person[]> & { available: Record<Category, Candidate[]>; limitations?: Partial<Record<Category, string>> };
const categories: Array<{ key: Category; label: string; icon: typeof Users }> = [
  { key: "athletes", label: "Athlètes", icon: UserRound }, { key: "arbitres", label: "Arbitres", icon: Flag }, { key: "officiels", label: "Officiels", icon: BadgeCheck }, { key: "medecins", label: "Médecins", icon: Stethoscope }, { key: "autres", label: "Autres", icon: Users },
];
const empty: Payload = { athletes: [], arbitres: [], officiels: [], medecins: [], autres: [], available: { athletes: [], arbitres: [], officiels: [], medecins: [], autres: [] } };

export function CompetitionPeoplePanel({ competitionId, readOnly = false }: { competitionId: string; readOnly?: boolean }) {
  const [data, setData] = useState<Payload>(empty), [category, setCategory] = useState<Category>("athletes"), [query, setQuery] = useState(""), [validityFilter, setValidityFilter] = useState("TOUS"), [loading, setLoading] = useState(true), [error, setError] = useState(""), [federal, setFederal] = useState(false);
  const [adding, setAdding] = useState(false), [candidateQuery, setCandidateQuery] = useState(""), [selectedId, setSelectedId] = useState(""), [role, setRole] = useState(""), [observations, setObservations] = useState("");
  useEffect(() => { let active = true; void fetch(`/api/competitions/${encodeURIComponent(competitionId)}/people`, { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.error || "Lecture impossible."); if (active) setData(payload); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Lecture impossible."); }).finally(() => { if (active) setLoading(false); }); void fetch("/api/auth/me").then((response) => response.json()).then((payload) => { if (active) setFederal(!readOnly && payload?.user?.role === "federal"); }); return () => { active = false; }; }, [competitionId, readOnly]);
  const people = useMemo(() => data[category].filter((person) => (validityFilter === "TOUS" || person.statutParticipation === validityFilter) && Object.values(person).join(" ").toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr"))), [category, data, query, validityFilter]);
  const candidates = useMemo(() => { const needle = candidateQuery.trim().toLocaleLowerCase("fr"); if (!needle) return []; return data.available[category].filter((person) => `${person.id} ${person.nom} ${person.club} ${person.equipe} ${person.grade}`.toLocaleLowerCase("fr").includes(needle)).slice(0, 20); }, [candidateQuery, category, data.available]);
  const selected = data.available[category].find((person) => person.selectionId === selectedId);
  const add = async () => { if (!selected || (category === "autres" && !role.trim())) return; setAdding(true); setError(""); try { const response = await fetch(`/api/competitions/${encodeURIComponent(competitionId)}/people`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, actorId: selected.id, unitId: selected.unitId, role, observations }) }), payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || "Enregistrement impossible."); setData(payload); setCandidateQuery(""); setSelectedId(""); setRole(""); setObservations(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setAdding(false); } };
  if (loading) return <p className="py-8 text-center text-muted-foreground"><Loader2 className="mr-2 inline size-4 animate-spin"/>Chargement des intervenants…</p>;
  const resetSelection = (key: Category) => { setCategory(key); setQuery(""); setValidityFilter("TOUS"); setCandidateQuery(""); setSelectedId(""); setRole(""); setObservations(""); };
  return <section className="space-y-5">
    <div><h2 className="text-lg font-semibold">Intervenants de la compétition</h2><p className="text-sm text-muted-foreground">La validité de participation est calculée à partir de la saison ou des dates de la compétition. Elle reste informative.</p></div>
    {error ? <p role="alert" className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</p> : null}
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{categories.map(({ key, label, icon: Icon }) => <button key={key} type="button" onClick={() => resetSelection(key)} className={cn("rounded-xl border p-4 text-left transition-colors", category === key ? "border-primary bg-primary/10" : "bg-card hover:bg-muted/50")}><div className="flex items-center justify-between"><Icon className={cn("size-5", category === key ? "text-primary" : "text-muted-foreground")}/><span className="text-2xl font-bold tabular-nums">{data[key].length}</span></div><p className="mt-3 text-sm font-medium">{label}</p></button>)}</div>
    {federal ? <Card className="gap-4 py-5 shadow-sm"><CardContent className="space-y-4 px-5"><div><h3 className="font-semibold">Ajouter un intervenant</h3><p className="text-sm text-muted-foreground">{category === "athletes" ? "Seuls les athlètes affiliés à une équipe engagée sont proposés." : `Recherchez une personne dans le registre ${categories.find((item) => item.key === category)?.label.toLocaleLowerCase("fr")}.`}</p></div><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={candidateQuery} onChange={(event) => { setCandidateQuery(event.target.value); setSelectedId(""); }} placeholder="Saisir un nom ou un identifiant…" className="pl-9"/></div>{candidateQuery && !selectedId ? <div className="max-h-64 overflow-y-auto rounded-lg border">{candidates.length ? candidates.map((candidate) => <button key={candidate.selectionId} type="button" onClick={() => { setSelectedId(candidate.selectionId); setCandidateQuery(candidate.nom); }} className="flex w-full items-center gap-3 border-b p-3 text-left last:border-b-0 hover:bg-muted/50"><Initials name={candidate.nom}/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{candidate.nom}</strong><small className="block truncate text-muted-foreground">{candidate.id}{candidate.equipe !== "-" ? ` · ${candidate.equipe}` : candidate.grade ? ` · ${candidate.grade}` : ""}</small></span></button>) : <p className="p-4 text-center text-sm text-muted-foreground">Aucune personne disponible.</p>}</div> : null}{selected ? <CandidatePreview category={category} person={selected}/> : null}{category === "autres" && selected ? <div className="space-y-1"><label htmlFor="competition-other-role" className="text-sm font-medium">Rôle dans la compétition</label><Input id="competition-other-role" value={role} onChange={(event) => setRole(event.target.value)} placeholder="Ex. Logisticien"/></div> : null}{selected ? <div className="space-y-1"><label htmlFor="competition-person-observations" className="text-sm font-medium">Observations</label><Input id="competition-person-observations" value={observations} onChange={(event) => setObservations(event.target.value)}/></div> : null}<Button onClick={() => void add()} disabled={adding || !selectedId || (category === "autres" && !role.trim())}>{adding ? <Loader2 className="animate-spin"/> : <Plus/>}Ajouter l’intervenant</Button></CardContent></Card> : null}
    <div className="flex flex-col gap-3 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un intervenant…" className="pl-9"/></div><label className="sr-only" htmlFor="participation-status-filter">Statut de participation</label><select id="participation-status-filter" value={validityFilter} onChange={(event) => setValidityFilter(event.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="TOUS">Tous les statuts</option><option value="VALIDE">Valide</option><option value="NON_VALIDE">Non valide</option><option value="NON_APPLICABLE">Non applicable</option><option value="INDETERMINE">Indéterminé</option></select></div>
    {data.limitations?.[category] ? <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">{data.limitations[category]}</p> : null}
    {people.length ? <PeopleList category={category} people={people}/> : <div className="rounded-xl border border-dashed p-10 text-center"><Users className="mx-auto size-8 text-muted-foreground/60"/><p className="mt-3 font-medium">Aucun intervenant dans cette catégorie</p></div>}
  </section>;
}

function CandidatePreview({ category, person }: { category: Category; person: Candidate }) { return <div className="space-y-2 rounded-lg border border-primary/30 bg-primary/5 p-3"><div className="flex items-center gap-3"><Check className="size-5 text-primary"/><div><p className="font-medium">{person.nom}</p><p className="text-xs text-muted-foreground">{person.id}{person.equipe !== "-" ? ` · ${person.equipe}` : ""}</p></div></div>{category === "arbitres" ? <Meta label="Grade" value={person.grade}/> : null}{category !== "autres" ? <div className="grid gap-2 sm:grid-cols-2"><Meta label="Licence trouvée" value={person.numeroLicence || "Numéro non renseigné"}/><ValidityBadge person={person}/>{person.dateDebutValidite || person.dateFinValidite ? <Meta label="Validité" value={`${formatDisplayDate(person.dateDebutValidite || "")} au ${formatDisplayDate(person.dateFinValidite || "")}`}/> : null}</div> : null}{person.statutParticipation === "NON_VALIDE" ? <p className="text-sm text-amber-700">Aucune licence valable n’a été trouvée pour cette compétition. L’intervenant peut néanmoins être ajouté.</p> : null}</div>; }

function PeopleList({ category, people }: { category: Category; people: Person[] }) {
  const secondaryLabel = category === "athletes" ? "Équipe" : category === "arbitres" ? "Grade" : category === "autres" ? "Rôle dans la compétition" : category === "medecins" ? "Spécialité" : "Numéro de licence";
  const secondary = (person: Person) => category === "athletes" ? person.equipe : category === "arbitres" ? person.grade : category === "autres" ? person.role || "Non renseigné" : category === "medecins" ? person.detail : person.numeroLicence || "—";
  const hasSeparateLicense = category !== "officiels";
  const grid = hasSeparateLicense ? "md:grid-cols-[minmax(180px,1.5fr)_minmax(140px,1fr)_minmax(130px,.8fr)_minmax(150px,1fr)_70px]" : "md:grid-cols-[minmax(180px,1.5fr)_minmax(140px,1fr)_minmax(150px,1fr)_70px]";
  return <Card className="gap-0 overflow-hidden py-0 shadow-sm"><CardContent className="p-0"><div className={cn("hidden bg-muted/35 text-xs font-semibold uppercase tracking-wide text-muted-foreground md:grid", grid)}><span className="p-3">Nom</span><span className="p-3">{secondaryLabel}</span>{hasSeparateLicense ? <span className="p-3">Licence</span> : null}<span className="p-3">Statut de participation</span><span className="p-3">Actions</span></div>{people.map((person) => <div key={`${category}-${person.id}`} className="border-t first:border-t-0"><div className={cn("hidden items-center text-sm md:grid", grid)}><Name person={person}/><span className="p-3">{secondary(person)}</span>{hasSeparateLicense ? <span className="p-3">{category === "autres" ? "Non applicable" : person.numeroLicence || "—"}</span> : null}<span className="p-3"><ValidityBadge person={person}/></span><span className="p-3 text-muted-foreground">—</span></div><div className="p-4 md:hidden"><Name person={person}/><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Meta label={secondaryLabel} value={secondary(person)}/>{hasSeparateLicense ? <Meta label="Licence" value={category === "autres" ? "Non applicable" : person.numeroLicence || "—"}/> : null}<ValidityBadge person={person}/></div></div></div>)}</CardContent></Card>;
}
function ValidityBadge({ person }: { person: Person }) { const labels: Record<Validity, string> = { VALIDE: "Valide", NON_VALIDE: "Non valide", NON_APPLICABLE: "Non applicable", INDETERMINE: "Indéterminé" }; return <span className="space-y-1" title={person.raisonStatutParticipation}><Badge aria-label={`${labels[person.statutParticipation]} : ${person.raisonStatutParticipation}`} variant={person.statutParticipation === "VALIDE" ? "default" : person.statutParticipation === "NON_VALIDE" ? "destructive" : "secondary"}>{labels[person.statutParticipation]}</Badge><small className="block text-muted-foreground">{person.raisonStatutParticipation}</small></span>; }
function Name({ person }: { person: Person }) { return <span className="flex min-w-0 items-center gap-3 p-3"><Initials name={person.nom}/><span><strong className="block break-words font-medium">{person.nom}</strong><small className="font-mono text-muted-foreground">{person.id}</small></span></span>; }
function Initials({ name }: { name: string }) { return <span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</span>; }
function Meta({ label, value }: { label: string; value: string }) { return <span><small className="block text-muted-foreground">{label}</small><span className="break-words">{value}</span></span>; }
