"use client"
import { useCallback, useEffect, useState } from "react"
import { Search } from "lucide-react"
import { AnalyticsTable, DashboardSection, StatusText } from "@/components/dashboard/analytics"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Progress } from "@/components/ui/progress"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import type { DataQualityIssue, DataQualitySummary } from "@/lib/data-quality/types"

const level=(status:string)=>status==="EXCELLENT"||status==="GOOD"?"good" as const:status==="CRITICAL"||status==="UNAVAILABLE"?"critical" as const:status==="INCOMPLETE"?"warning" as const:"neutral" as const
const statusLabel:Record<string,string>={EXCELLENT:"Excellent",GOOD:"Bon",INCOMPLETE:"Incomplet",CRITICAL:"Critique",NOT_EVALUATED:"Aucune donnée",UNAVAILABLE:"Indisponible"}
export function DataQualitySection({refreshKey=0}:{refreshKey?:number}){const[data,setData]=useState<DataQualitySummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[issues,setIssues]=useState<DataQualityIssue[]>([]),[issueTotal,setIssueTotal]=useState(0),[issueLoading,setIssueLoading]=useState(false),[block,setBlock]=useState(""),[search,setSearch]=useState("")
 const load=useCallback(async(fresh=false)=>{setLoading(true);setError("");try{const response=await fetch(`/api/dashboard/data-quality${fresh?"?fresh=1":""}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload?.error||"Lecture impossible");setData(payload)}catch(e){setError(e instanceof Error?e.message:"Lecture impossible")}finally{setLoading(false)}},[])
 useEffect(()=>{void load(refreshKey>0)},[load,refreshKey])
 const loadIssues=useCallback(async(targetBlock=block,targetSearch=search)=>{setIssueLoading(true);try{const q=new URLSearchParams({pageSize:"50"});if(data?.seasonId)q.set("seasonId",data.seasonId);if(targetBlock)q.set("block",targetBlock);if(targetSearch)q.set("search",targetSearch);const response=await fetch(`/api/dashboard/data-quality/issues?${q}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload?.error||"Lecture impossible");setIssues(payload.items||[]);setIssueTotal(payload.total||0)}catch{setIssues([]);setIssueTotal(0)}finally{setIssueLoading(false)}},[block,search,data?.seasonId])
 const showIssues=(targetBlock="")=>{setBlock(targetBlock);setSearch("");setOpen(true);void loadIssues(targetBlock,"")}
 return <DashboardSection title="Qualité des données" description="Complétude pondérée des sept blocs métier, calculée côté serveur.">
  {error?<div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">{error}</div>:null}
  {data?<AnalyticsTable rows={data.blocks} columns={[{key:"label",label:"Bloc métier",render:(row)=><div><p className="font-medium">{String(row.label)}</p><p className="mt-0.5 text-xs text-muted-foreground">{row.complete} complètes · {row.partial} partielles · {row.critical} critiques</p></div>},{key:"records",label:"Fiches",align:"right"},{key:"score",label:"Complétude",render:(row)=><div className="min-w-44 space-y-1.5"><div className="flex justify-between text-xs"><span className="font-medium">{row.score==null?"Aucune donnée":`${row.score} %`}</span><StatusText level={level(String(row.status))}>{statusLabel[String(row.status)]||String(row.status)}</StatusText></div><Progress value={row.score??0} aria-label={`Complétude ${row.label}`}/></div>},{key:"issues",label:"À corriger",align:"right",render:(row)=>Number(row.issueCount)?<Button variant="ghost" size="sm" onClick={()=>showIssues(String(row.block))}>{String(row.issueCount)} fiche{Number(row.issueCount)>1?"s":""}</Button>:<StatusText level="good">Aucune</StatusText>}]}/>:loading?<p className="text-sm text-muted-foreground">Calcul de la complétude…</p>:null}
  <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Fiches à corriger</SheetTitle><SheetDescription>{issueTotal} anomalie{issueTotal>1?"s":""}{block?" dans le bloc sélectionné":""}.</SheetDescription></SheetHeader><div className="space-y-4 px-4 pb-6"><div className="flex gap-2"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Identifiant, fiche ou champ…" onKeyDown={e=>{if(e.key==="Enter")void loadIssues()}}/><Button variant="outline" size="icon" aria-label="Rechercher" onClick={()=>void loadIssues()}><Search/></Button></div>{issueLoading?<p className="py-8 text-center text-sm text-muted-foreground">Chargement…</p>:<div className="space-y-2">{issues.map((issue,index)=><div key={`${issue.block}-${issue.entityId}-${issue.field}-${index}`} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{issue.entityLabel}</p><p className="text-xs text-muted-foreground">{issue.entityType} · {issue.entityId}</p></div><StatusText level={issue.severity==="CRITICAL"?"critical":issue.severity==="WARNING"?"warning":"neutral"}>{issue.fieldLabel}</StatusText></div><p className="mt-2 text-sm">{issue.message}</p></div>)}{!issues.length?<p className="py-8 text-center text-sm text-muted-foreground">Aucune anomalie pour ces filtres.</p>:null}</div>}</div></SheetContent></Sheet>
 </DashboardSection>}
