"use client"
import { useEffect, useMemo, useState } from "react"
import { Check, Search } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { useToast } from "@/hooks/use-toast"
import { searchLicenceOptions, sanitizeLicenceOptions } from "@/lib/licence-options"

type Option={id:string;label:string}
export type LicenceView={id:string;athleteId:string;athleteNom:string;sexId:string;sexe:string;affiliationId:string;equipeId:string;equipeNom:string;clubId:string;clubNom:string;ententeId:string;ententeNom:string;ligueId:string;ligueNom:string;seasonId:string;saison:string;numero:string;dateDelivrance:string;statusId:string;statut:string;observations:string}
type Candidate={affiliationId:string;athleteId:string;athleteNom:string;sexe:string;teamId:string;teamName:string;clubName:string;alreadyLicensed:boolean;existingLicence:LicenceView|null;previousNumber:string;previousSeason:string;situation:string}
type References={seasons:Option[];statuses:Option[];teams:Option[];athletes:Option[]}

function SearchPicker({value,onChange,options,placeholder,disabled}:{value:string;onChange:(id:string)=>void;options:Option[];placeholder:string;disabled?:boolean}){const selected=options.find(x=>x.id===value),[query,setQuery]=useState(selected?.label||""),[focused,setFocused]=useState(false),results=useMemo(()=>searchLicenceOptions(options,query),[options,query]);useEffect(()=>setQuery(selected?.label||""),[selected?.id,selected?.label]);return <div className="relative"><Search className="absolute left-3 top-3 z-10 size-4 text-muted-foreground"/><Input className="pl-9" value={query} disabled={disabled} placeholder={placeholder} autoComplete="off" onFocus={()=>setFocused(true)} onBlur={()=>window.setTimeout(()=>setFocused(false),150)} onChange={e=>{setQuery(e.target.value);onChange("")}}/>{focused&&!disabled?<div className="absolute z-50 mt-1 max-h-64 w-full overflow-y-auto rounded-md border bg-popover p-1 shadow-md">{query.trim().length<2?<p className="p-2 text-sm text-muted-foreground">Saisissez au moins 2 caractères.</p>:results.length?results.map(x=><button key={x.id} type="button" className="block w-full rounded-sm px-3 py-2 text-left text-sm hover:bg-accent" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.id);setQuery(x.label);setFocused(false)}}>{x.label}<span className="ml-2 text-xs text-muted-foreground">{x.id}</span></button>):<p className="p-2 text-sm text-muted-foreground">Aucun résultat.</p>}</div>:null}</div>}
const today=()=>new Date().toISOString().slice(0,10)

export function LicenceEditor({open,onOpenChange,references,editing,initialMode="ATHLETE",readOnly=false,onSaved}:{open:boolean;onOpenChange:(open:boolean)=>void;references:References;editing?:LicenceView|null;initialMode?:"ATHLETE"|"EQUIPE";readOnly?:boolean;onSaved:()=>void}){
 const {toast}=useToast(),refs=useMemo(()=>({seasons:sanitizeLicenceOptions(references.seasons),statuses:sanitizeLicenceOptions(references.statuses),teams:sanitizeLicenceOptions(references.teams)}),[references]);const[mode,setMode]=useState<"ATHLETE"|"EQUIPE">(initialMode),[seasonId,setSeasonId]=useState(""),[teamId,setTeamId]=useState(""),[athleteId,setAthleteId]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState<string[]>([]),[numero,setNumero]=useState(""),[date,setDate]=useState(today()),[statusId,setStatusId]=useState("STL001"),[observations,setObservations]=useState(""),[search,setSearch]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[errors,setErrors]=useState<Record<string,string>>({});const candidate=candidates.find(x=>x.athleteId===athleteId),existing=editing||candidate?.existingLicence||null
 useEffect(()=>{if(!open)return;setErrors({});setCandidates([]);setSelected([]);setSearch("");if(editing){setMode("ATHLETE");setSeasonId(editing.seasonId);setTeamId(editing.equipeId);setAthleteId(editing.athleteId);setNumero(editing.numero);setDate(editing.dateDelivrance);setStatusId(editing.statusId);setObservations(editing.observations)}else{setMode(initialMode);setSeasonId(refs.seasons.find(x=>x.label===String(new Date().getFullYear()))?.id||refs.seasons[0]?.id||"");setTeamId("");setAthleteId("");setNumero("");setDate(today());setStatusId("STL001");setObservations("")}},[open,editing,initialMode,refs.seasons])
 useEffect(()=>{if(!open||editing||!seasonId||!teamId){if(!editing)setCandidates([]);return}setLoading(true);setErrors({});const q=new URLSearchParams({mode:"EQUIPE",id_saison:seasonId,id_equipe:teamId});void fetch(`/api/licences/eligibilite?${q}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Éligibilité indisponible.");setCandidates(p.candidates||[])}).catch(e=>setErrors({_form:e instanceof Error?e.message:"Éligibilité indisponible."})).finally(()=>setLoading(false))},[open,editing,seasonId,teamId])
 useEffect(()=>{if(editing||mode!=="ATHLETE")return;if(candidate?.existingLicence){setNumero(candidate.existingLicence.numero);setDate(candidate.existingLicence.dateDelivrance);setStatusId(candidate.existingLicence.statusId);setObservations(candidate.existingLicence.observations)}else{setNumero("");setDate(today());setStatusId("STL001");setObservations("")}},[candidate,editing,mode])
 const available=candidates.filter(x=>x.situation==="Renouvelable"),visible=candidates.filter(x=>`${x.athleteNom} ${x.athleteId}`.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))),athleteOptions=candidates.map(x=>({id:x.athleteId,label:x.athleteNom}));const chooseSeason=(id:string)=>{setSeasonId(id);setAthleteId("");setSelected([])},chooseTeam=(id:string)=>{setTeamId(id);setAthleteId("");setSelected([])}
 const select=(value:string,onChange:(id:string)=>void,options:Option[],disabled=false)=><Select value={value} onValueChange={onChange} disabled={disabled||saving}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select>
 const submit=async()=>{if(saving||readOnly)return;setSaving(true);setErrors({});const body=existing?{numero_licence:numero,date_delivrance:date,id_statut_licence:statusId,observations}:mode==="ATHLETE"?{mode,id_saison:seasonId,id_affiliation_athlete:candidate?.affiliationId,numero_licence:numero,date_delivrance:date,id_statut_licence:statusId,observations}:{mode,id_saison:seasonId,id_equipe:teamId,id_affiliations_athletes:selected,date_delivrance:date,id_statut_licence:"STL001",observations};try{const r=await fetch(existing?`/api/licences/${encodeURIComponent(existing.id)}`:"/api/licences/renouveler",{method:existing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json();if(!r.ok){setErrors({...p?.error?.fields,_form:p?.error?.message||"Enregistrement impossible."});return}toast({title:existing?"Licence modifiée":mode==="EQUIPE"?`${p.length||selected.length} licence(s) renouvelée(s)`:"Licence enregistrée",description:mode==="EQUIPE"?"Le renouvellement collectif a été ajouté à l’historique.":"Les données de licence ont été actualisées."});onSaved();onOpenChange(false)}catch{setErrors({_form:"Service temporairement indisponible."})}finally{setSaving(false)}}
 return <Sheet open={open} onOpenChange={n=>!saving&&onOpenChange(n)}><SheetContent className="w-full overflow-y-auto sm:max-w-3xl"><SheetHeader><SheetTitle>{readOnly?"Consulter la licence":existing?"Modifier la licence":mode==="EQUIPE"?"Renouveler les licences d’une équipe":"Enregistrer une licence"}</SheetTitle><SheetDescription>La licence reste liée à une affiliation réelle et à une saison annuelle.</SheetDescription></SheetHeader><fieldset disabled={readOnly} className="space-y-5 px-4 pb-28"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Saison *</Label>{select(seasonId,chooseSeason,refs.seasons,!!editing)}</div><div className="space-y-2"><Label>Équipe *</Label><SearchPicker value={teamId} onChange={chooseTeam} options={refs.teams} placeholder="Rechercher une équipe" disabled={!!editing||saving}/></div>{mode==="ATHLETE"?<div className="space-y-2 sm:col-span-2"><Label>Athlète *</Label><SearchPicker value={athleteId} onChange={setAthleteId} options={athleteOptions} placeholder={teamId?"Rechercher parmi les affiliés":"Sélectionnez d’abord une équipe"} disabled={!teamId||!!editing||saving}/>{candidate?<p className="text-xs text-muted-foreground">Affiliation {candidate.affiliationId} · {candidate.clubName}</p>:null}</div>:null}</div>
 {mode==="EQUIPE"&&teamId?<div className="space-y-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm"><strong>{selected.length}</strong> sélectionné(s) · {available.length} renouvelable(s)</p><Button type="button" size="sm" variant="outline" onClick={()=>setSelected(available.map(x=>x.affiliationId))}>Tout sélectionner</Button></div><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher dans l’équipe"/><div className="max-h-80 space-y-2 overflow-y-auto">{visible.map(x=>{const enabled=x.situation==="Renouvelable";return <label key={x.affiliationId} className="flex items-center gap-3 rounded-lg border p-3"><Checkbox checked={selected.includes(x.affiliationId)} disabled={!enabled} onCheckedChange={v=>setSelected(c=>v?[...c,x.affiliationId]:c.filter(id=>id!==x.affiliationId))}/><span className="min-w-0 flex-1"><span className="block font-medium">{x.athleteNom}</span><span className="block text-xs text-muted-foreground">{x.sexe||"Sexe non défini"} · N° précédent {x.previousNumber||"-"} · {x.previousSeason||"-"}</span></span><span className="text-xs font-medium">{x.situation==="Première licence requise"?"Première licence à enregistrer individuellement":x.situation}</span>{enabled?<Check className="size-4 text-primary"/>:null}</label>})}</div></div>:null}
 {loading?<p className="text-sm text-muted-foreground">Chargement des affiliations…</p>:null}<div className="grid gap-4 sm:grid-cols-2">{mode==="ATHLETE"?<div className="space-y-2"><Label>Numéro de licence *</Label><Input value={numero} onChange={e=>setNumero(e.target.value)} aria-invalid={!!errors.numero_licence}/>{errors.numero_licence?<p className="text-sm text-destructive">{errors.numero_licence}</p>:null}</div>:null}<div className="space-y-2"><Label>Date de délivrance *</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{mode==="ATHLETE"?<div className="space-y-2"><Label>Statut *</Label>{select(statusId,setStatusId,refs.statuses)}</div>:null}<div className="space-y-2 sm:col-span-2"><Label>Observations</Label><Textarea value={observations} onChange={e=>setObservations(e.target.value)}/></div></div>{errors._form?<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{errors._form}</p>:null}</fieldset><SheetFooter className="absolute inset-x-0 bottom-0 border-t bg-background"><Button variant="outline" onClick={()=>onOpenChange(false)} disabled={saving}>{readOnly?"Fermer":"Annuler"}</Button>{readOnly?null:<Button onClick={()=>void submit()} disabled={saving||loading||!seasonId||!teamId||(mode==="ATHLETE"?!athleteId:!selected.length)}>{saving?"Enregistrement…":existing?"Enregistrer les modifications":mode==="EQUIPE"?`Renouveler ${selected.length} licence(s)`:"Enregistrer la licence"}</Button>}</SheetFooter></SheetContent></Sheet>
}
