"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { sanitizeLicenceOptions } from "@/lib/licence-options";

type Option = { id: string; label: string };
export type LicenceView = { id: string; athleteId: string; athleteNom: string; affiliationId: string; equipeId: string; equipeNom: string; clubNom: string; seasonId: string; saison: string; numero: string; dateDelivrance: string; statusId: string; statut: string; observations: string };
type Candidate = { affiliationId: string; athleteId: string; athleteNom: string; teamId: string; teamName: string; clubName: string; affiliationStatusId: string; alreadyLicensed: boolean; existingLicence: LicenceView | null };

const today = () => new Date().toISOString().slice(0, 10);
export function LicenceEditor({ open, onOpenChange, references, editing, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; references: { seasons: Option[]; statuses: Option[]; teams: Option[]; athletes: Option[] }; editing?: LicenceView | null; onSaved: () => void }) {
  const safeReferences = useMemo(() => ({ seasons: sanitizeLicenceOptions(references.seasons), statuses: sanitizeLicenceOptions(references.statuses), teams: sanitizeLicenceOptions(references.teams), athletes: sanitizeLicenceOptions(references.athletes) }), [references]);
  const [mode, setMode] = useState<"ATHLETE" | "EQUIPE">("ATHLETE"), [seasonId, setSeasonId] = useState(""), [athleteId, setAthleteId] = useState(""), [teamId, setTeamId] = useState(""), [candidates, setCandidates] = useState<Candidate[]>([]), [affiliationId, setAffiliationId] = useState(""), [selected, setSelected] = useState<string[]>([]), [search, setSearch] = useState(""), [numero, setNumero] = useState(""), [date, setDate] = useState(today()), [statusId, setStatusId] = useState("STL001"), [observations, setObservations] = useState(""), [saving, setSaving] = useState(false), [loading, setLoading] = useState(false), [errors, setErrors] = useState<Record<string, string>>({});
  const existing = editing || (mode === "ATHLETE" ? candidates.find((item) => item.existingLicence)?.existingLicence : null);
  useEffect(() => {
    if (!open) return;
    setErrors({}); setCandidates([]); setSelected([]); setSearch("");
    if (editing) { setMode("ATHLETE"); setSeasonId(editing.seasonId); setAthleteId(editing.athleteId); setAffiliationId(editing.affiliationId); setNumero(editing.numero); setDate(editing.dateDelivrance); setStatusId(editing.statusId); setObservations(editing.observations); }
    else { setMode("ATHLETE"); setSeasonId(safeReferences.seasons[0]?.id || ""); setAthleteId(""); setTeamId(""); setAffiliationId(""); setNumero(""); setDate(today()); setStatusId(safeReferences.statuses.some((item) => item.id === "STL001") ? "STL001" : safeReferences.statuses[0]?.id || ""); setObservations(""); }
  }, [open, editing, safeReferences]);
  useEffect(() => {
    if (!open || editing || !seasonId || (mode === "ATHLETE" ? !athleteId : !teamId)) { if (!editing) setCandidates([]); return; }
    const query = new URLSearchParams({ mode, id_saison: seasonId, ...(mode === "ATHLETE" ? { id_athlete: athleteId } : { id_equipe: teamId }) });
    setLoading(true); setErrors({});
    void fetch(`/api/licences/eligibilite?${query}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || "Éligibilité indisponible."); const next = data.candidates || []; setCandidates(next); if (mode === "ATHLETE") { const first = next[0]; setAffiliationId(first?.affiliationId || ""); if (first?.existingLicence) { setNumero(first.existingLicence.numero); setDate(first.existingLicence.dateDelivrance); setStatusId(first.existingLicence.statusId); setObservations(first.existingLicence.observations); } } }).catch((reason) => setErrors({ _form: reason instanceof Error ? reason.message : "Éligibilité indisponible." })).finally(() => setLoading(false));
  }, [open, editing, mode, seasonId, athleteId, teamId]);
  const available = candidates.filter((item) => !item.alreadyLicensed), visible = candidates.filter((item) => `${item.athleteNom} ${item.athleteId}`.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))), selectedCount = selected.length, alreadyCount = candidates.filter((item) => item.alreadyLicensed).length;
  const submit = async () => {
    if (saving) return; setSaving(true); setErrors({});
    const payload = existing ? { numero_licence: numero, date_delivrance: date, id_statut_licence: statusId, observations } : mode === "ATHLETE" ? { mode, id_saison: seasonId, id_affiliation_athlete: affiliationId, numero_licence: numero, date_delivrance: date, id_statut_licence: statusId, observations } : { mode, id_saison: seasonId, id_equipe: teamId, id_affiliations_athletes: selected, date_delivrance: date, id_statut_licence: statusId, observations };
    try { const response = await fetch(existing ? `/api/licences/${encodeURIComponent(existing.id)}` : "/api/licences/renouveler", { method: existing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }), data = await response.json(); if (!response.ok) { setErrors({ ...(data?.error?.fields || {}), _form: data?.error?.message || "Enregistrement impossible." }); return; } onSaved(); onOpenChange(false); }
    catch { setErrors({ _form: "Service temporairement indisponible." }); }
    finally { setSaving(false); }
  };
  const option = (value: string, setValue: (value: string) => void, options: Option[], placeholder: string, disabled = false) => <Select value={value} onValueChange={setValue} disabled={disabled || saving}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select>;
  return <Sheet open={open} onOpenChange={(next) => !saving && onOpenChange(next)}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{existing ? "Modifier la licence" : "Renouveler des licences"}</SheetTitle><SheetDescription>Une licence d’athlète est toujours liée à une affiliation réelle et à une saison.</SheetDescription></SheetHeader><div className="space-y-5 px-4 pb-28">
    {!editing ? <div className="space-y-2"><Label>Renouvellement</Label><div className="grid grid-cols-2 gap-2 rounded-lg bg-muted p-1"><Button type="button" variant={mode === "ATHLETE" ? "default" : "ghost"} onClick={() => { setMode("ATHLETE"); setCandidates([]); setSelected([]); }}>Un athlète</Button><Button type="button" variant={mode === "EQUIPE" ? "default" : "ghost"} onClick={() => { setMode("EQUIPE"); setCandidates([]); setSelected([]); }}>Une équipe</Button></div></div> : null}
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Saison *</Label>{option(seasonId, setSeasonId, safeReferences.seasons, "Choisir une saison", !!editing)}</div>{mode === "ATHLETE" ? <div className="space-y-2"><Label>Athlète *</Label>{option(athleteId, setAthleteId, safeReferences.athletes, "Rechercher un athlète", !!editing)}</div> : <div className="space-y-2"><Label>Équipe *</Label>{option(teamId, setTeamId, safeReferences.teams, "Choisir une équipe")}</div>}</div>
    {mode === "ATHLETE" && !editing && candidates.length ? <div className="rounded-lg border p-3 text-sm"><p className="font-medium">{candidates[0].teamName}</p><p className="text-muted-foreground">{candidates[0].clubName} · Affiliation {candidates[0].affiliationId}</p>{existing ? <p className="mt-2 font-medium text-amber-600">Une licence existe déjà : vous modifiez la licence en cours.</p> : <p className="mt-2 font-medium text-primary">1 licence sera créée.</p>}</div> : null}
    {mode === "EQUIPE" && teamId ? <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{selectedCount} athlète{selectedCount > 1 ? "s" : ""} sélectionné{selectedCount > 1 ? "s" : ""}</p><p className="text-xs text-muted-foreground">{available.length} licences à créer · {alreadyCount} déjà licencié{alreadyCount > 1 ? "s" : ""}</p></div><div className="flex gap-2"><Button type="button" size="sm" variant="outline" onClick={() => setSelected(available.map((item) => item.affiliationId))}>Tout sélectionner</Button><Button type="button" size="sm" variant="ghost" onClick={() => setSelected([])}>Tout désélectionner</Button></div></div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher dans l’équipe"/></div><div className="grid max-h-72 gap-2 overflow-y-auto">{visible.map((item) => <label key={item.affiliationId} className="flex cursor-pointer items-start gap-3 rounded-lg border p-3 has-[:checked]:border-primary"><Checkbox checked={selected.includes(item.affiliationId)} disabled={item.alreadyLicensed} onCheckedChange={(checked) => setSelected((current) => checked ? [...current, item.affiliationId] : current.filter((id) => id !== item.affiliationId))} aria-label={`Sélectionner ${item.athleteNom}`}/><span className="min-w-0 flex-1"><span className="block font-medium">{item.athleteNom}</span><span className="block text-xs text-muted-foreground">{item.athleteId} · {item.affiliationId} · {item.affiliationStatusId}</span></span>{item.alreadyLicensed ? <span className="rounded-full bg-muted px-2 py-1 text-xs">Déjà licencié</span> : <Check className="h-4 w-4 text-primary"/>}</label>)}</div></div> : null}
    {loading ? <p className="text-sm text-muted-foreground">Chargement des affiliations…</p> : null}
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Numéro de licence</Label><Input value={numero} onChange={(event) => setNumero(event.target.value)}/></div><div className="space-y-2"><Label>Date de délivrance *</Label><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} aria-invalid={!!errors.date_delivrance}/></div><div className="space-y-2"><Label>Statut *</Label>{option(statusId, setStatusId, safeReferences.statuses, "Choisir un statut")}</div><div className="space-y-2 sm:col-span-2"><Label>Observations</Label><Textarea value={observations} onChange={(event) => setObservations(event.target.value)}/></div></div>
    {errors._form ? <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{errors._form}</p> : null}
  </div><SheetFooter className="absolute inset-x-0 bottom-0 border-t bg-background"><Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>Annuler</Button><Button onClick={() => void submit()} disabled={saving || loading || !seasonId || (mode === "ATHLETE" ? !affiliationId : !selected.length)}>{saving ? "Enregistrement…" : existing ? "Enregistrer les modifications" : mode === "EQUIPE" ? `Créer ${selectedCount} licence${selectedCount > 1 ? "s" : ""}` : "Créer la licence"}</Button></SheetFooter></SheetContent></Sheet>;
}
