"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, Loader2 } from "lucide-react"
import { Header } from "@/components/dashboard/header"
import { FederalEditLink } from "@/components/dashboard/federal-edit-link"
import { StatusBadge } from "@/components/dashboard/status-badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
type Kind = "ententes" | "equipes"
const labels: Record<string, string> = { id: "Identifiant", nom: "Nom", sigle: "Sigle", ligue: "Ligue", entente: "Entente", club: "Club", province: "Province", categorie: "Catégorie", genre: "Sexe", email: "E-mail", telephone: "Téléphone", date_creation: "Date de création", date_reconnaissance: "Date de reconnaissance" }
export function TerritorialDetail({ kind, id }: { kind: Kind; id: string }) {
  const router = useRouter(); const [item, setItem] = useState<Record<string, unknown> | null>(null); const [members, setMembers] = useState<Record<string, Record<string, string>[]>>({ athletes: [], coachs: [], medecins: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  useEffect(() => { void Promise.all([fetch(`/api/${kind}`, { cache: "no-store" }), kind === "equipes" ? Promise.all(["athlete", "coach", "medecin"].map((type) => fetch(`/api/affiliations/${type}?equipeId=${encodeURIComponent(id)}`, { cache: "no-store" }))) : Promise.resolve(null)]).then(async ([response, affiliationResponses]) => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.error || "Lecture impossible."); const found = (payload[kind] || []).find((candidate: Record<string, unknown>) => String(candidate.id) === id); if (!found) throw new Error("Élément introuvable."); setItem(found); if (affiliationResponses) { const payloads = await Promise.all(affiliationResponses.map((res) => res.json())); if (affiliationResponses.some((res) => !res.ok)) throw new Error("Lecture des affiliations impossible."); setMembers({ athletes: payloads[0].affiliations || [], coachs: payloads[1].affiliations || [], medecins: payloads[2].affiliations || [] }) } }).catch((cause) => setError(cause instanceof Error ? cause.message : "Lecture impossible.")).finally(() => setLoading(false)) }, [kind, id])
  if (loading) return <><Header title="Chargement…" /><p className="p-6 text-muted-foreground"><Loader2 className="mr-2 inline animate-spin" />Chargement…</p></>
  if (error || !item) return <><Header title="Élément introuvable" /><div className="p-6"><p className="text-destructive">{error}</p><Button className="mt-4" onClick={() => router.back()}>Retour</Button></div></>
  const name = String(item.nom || "Non renseigné"), fields = Object.entries(labels).filter(([key]) => !["nom", "id"].includes(key)).map(([key, label]) => ({ label, value: String(item[key] || "Non renseigné") }))
  return <div><Header title={`${kind === "ententes" ? "Fiche Entente" : "Fiche Équipe"} : ${name}`} /><main className="space-y-6 p-4 md:p-6"><div className="flex items-center justify-between gap-3"><Button variant="outline" onClick={() => router.back()}><ArrowLeft />Retour</Button><FederalEditLink href={`/dashboard/${kind}?edit=${encodeURIComponent(id)}`} /></div><Card><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-2xl">{name}</CardTitle><p className="mt-2 font-mono text-sm text-muted-foreground">{id}</p></div><StatusBadge status={String(item.statut || "")} /></div></CardHeader></Card><Card><CardHeader><CardTitle>Informations générales</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2">{fields.map((field) => <div key={field.label}><p className="text-sm text-muted-foreground">{field.label}</p><p className="mt-1 font-medium">{field.value}</p></div>)}</CardContent></Card>
  {kind === "equipes" ? <div className="grid gap-6 lg:grid-cols-3">{([['athletes','Athlètes'],['coachs','Coachs'],['medecins','Médecins']] as const).map(([key,label]) => <Card key={key}><CardHeader><CardTitle>{label} affiliés ({members[key].length})</CardTitle></CardHeader><CardContent><div className="grid gap-3">{members[key].length ? members[key].map((member) => <div key={member.id} className="rounded-lg border p-3"><p className="font-medium">{member.nomActeur || "Référence inconnue"}</p>{member.fonction ? <p className="text-sm">{member.fonction}</p> : null}<p className="text-sm text-muted-foreground">{member.date_debut} — {member.date_fin || "En cours"}</p><StatusBadge status={member.statut} />{member.anomalie ? <p className="mt-2 text-sm text-destructive">{member.anomalie}</p> : null}</div>) : <p className="text-muted-foreground">Aucune affiliation.</p>}</div></CardContent></Card>)}</div> : null}<Card><CardHeader><CardTitle>Observations</CardTitle></CardHeader><CardContent>{String(item.observations || item.observation || "Non renseigné")}</CardContent></Card></main></div>
}
