"use client"

import { useEffect, useMemo, useState } from "react"
import { DataTable,type Column,type Filter } from "@/components/dashboard/data-table"
import { Header } from "@/components/dashboard/header"
import { StatusBadge } from "@/components/dashboard/status-badge"
import { nationalScoreLabel } from "@/lib/equipe-nationale-utils"
import { getFilterOptions,type ResultatEquipeNationale } from "@/lib/models"
const columns:Column<ResultatEquipeNationale>[]=[{key:"id",header:"ID résultat",className:"font-mono text-sm"},{key:"dateMatch",header:"Date"},{key:"equipeNationaleNom",header:"Équipe nationale"},{key:"competitionNom",header:"Compétition"},{key:"phase",header:"Phase"},{key:"nomAdversaire",header:"Adversaire",className:"font-medium"},{key:"paysAdversaire",header:"Pays"},{key:"scoreTotalA",header:"Score",render:nationalScoreLabel},{key:"uniteVainqueurNom",header:"Vainqueur"},{key:"statutMatch",header:"Statut",render:item=><StatusBadge status={item.statutMatch}/>}]
export default function ResultatsPage(){const[data,setData]=useState<ResultatEquipeNationale[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;(async()=>{try{const r=await fetch("/api/equipe-nationale-resultats",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Lecture impossible");if(active)setData(j.resultats||[])}catch(e){if(active)setError(e instanceof Error?e.message:"Lecture impossible")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);const filters:Filter[]=useMemo(()=>["equipeNationaleNom","discipline","categorie","sexe","competitionNom","phase","paysAdversaire","statutMatch"].map(key=>({key,label:({equipeNationaleNom:"Équipe nationale",discipline:"Discipline",categorie:"Catégorie",sexe:"Sexe",competitionNom:"Compétition",phase:"Phase",paysAdversaire:"Pays",statutMatch:"Statut"}as Record<string,string>)[key],options:getFilterOptions(data,key as keyof ResultatEquipeNationale)})),[data]);return <div className="flex flex-col"><Header title="Résultats des équipes nationales" subtitle={`${data.length} match${data.length>1?"s":""}`}/><div className="p-6">{loading?<p className="text-muted-foreground">Chargement...</p>:error?<p className="text-destructive">{error}</p>:<DataTable data={data} columns={columns} filters={filters} searchPlaceholder="Équipe, compétition, adversaire ou identifiant..." detailHref={item=>`/dashboard/equipe-nationale/resultats/${encodeURIComponent(item.id)}`} idKey="__key"/>}</div></div>}
