import assert from "node:assert/strict";import test from "node:test";import {ActorLicenseError,createActorLicense,generateActorLicenseId,getEffectiveLicenseStatus,listActorLicenses,updateActorLicense,updateActorLicenseStatus}from"../lib/actor-licences";import type{SheetRow}from"../lib/google-sheets"
const base:Record<string,SheetRow[]>={ACTEURS_LICENCES:[],TYPES_ACTEURS:[{id_type_acteur:"TAC001",nom_type_acteur:"ATHLETE"},{id_type_acteur:"TAC002",nom_type_acteur:"COACH"},{id_type_acteur:"TAC003",nom_type_acteur:"OFFICIEL"},{id_type_acteur:"TAC004",nom_type_acteur:"ARBITRE"},{id_type_acteur:"TAC005",nom_type_acteur:"MEDECIN"}],CYCLES_LICENCES:[{id_cycle_licence:"CYC001",nom_cycle_licence:"SPORTIF"},{id_cycle_licence:"CYC002",nom_cycle_licence:"ADMINISTRATIF"},{id_cycle_licence:"CYC003",nom_cycle_licence:"PERMANENT"}],STATUT_LICENCE:[{id_statut_licence:"STL001",nom_statut_licence:"ACTIVE"},{id_statut_licence:"STL002",nom_statut_licence:"EXPIREE"},{id_statut_licence:"STL003",nom_statut_licence:"SUSPENDUE"},{id_statut_licence:"STL004",nom_statut_licence:"CLOTUREE"},{id_statut_licence:"STL005",nom_statut_licence:"ANNULEE"}],COACHS:[{id_coach:"COA1",nom_complet:"Coach Un"}],OFFICIELS:[{id_officiel:"OFF1",nom_complet:"Officiel Un"}],ARBITRES:[{id_arbitre:"ARB1",nom_complet:"Arbitre Un"}],MEDECINS:[{id_medecin:"MED1",nom_complet:"Médecin Un"}]}
function fixture(overrides:Record<string,SheetRow[]>={}){const sheets={...base,...overrides},appends:any[]=[],upserts:any[]=[];return{deps:{readRows:async({sheet}:{sheet:string})=>sheets[sheet]||[],appendRows:async(a:any)=>appends.push(a),upsertRows:async(a:any)=>upserts.push(a)}as never,appends,upserts}}
const payload={id_type_acteur:"TAC002",id_acteur:"COA1",id_cycle_licence:"CYC002",numero_licence:"001-A",date_delivrance:"2026-01-01",date_debut_validite:"2026-01-01",date_fin_validite:"2026-12-31",observations:""}
test("calcule les statuts effectifs sans fuseau horaire",()=>{assert.equal(getEffectiveLicenseStatus("ACTIVE","2026-01-01","2026-09-14","2026-09-14"),"VALIDE");assert.equal(getEffectiveLicenseStatus("ACTIVE","2026-01-01","2026-09-13","2026-09-14"),"EXPIREE");assert.equal(getEffectiveLicenseStatus("ACTIVE","2026-09-15","2026-12-31","2026-09-14"),"A_VENIR");assert.equal(getEffectiveLicenseStatus("SUSPENDUE","2026-01-01","2026-12-31","2026-09-14"),"SUSPENDUE")})
test("génère un identifiant acteur annuel global",()=>assert.equal(generateActorLicenseId("2026-01-01",[{id_licence:"BKB-ACL-2026-000009"}]),"BKB-ACL-2026-000010"))
test("crée une première licence dans les dix colonnes réelles",async()=>{const f=fixture(),row=await createActorLicense(payload,f.deps);assert.equal(row.numero_licence,"001-A");assert.equal(f.appends.length,1);assert.deepEqual(Object.keys(f.appends[0].rows[0].values),["id_licence","id_type_acteur","id_acteur","id_cycle_licence","numero_licence","date_delivrance","date_debut_validite","date_fin_validite","id_statut_licence","observations"])})
test("refuse types interdits, acteur incohérent, permanent et dates invalides",async()=>{for(const body of [{...payload,id_type_acteur:"TAC001"},{...payload,id_acteur:"OFF1"},{...payload,id_cycle_licence:"CYC003"},{...payload,date_delivrance:"2026-02-01",date_debut_validite:"2026-01-01"},{...payload,date_fin_validite:"2025-12-31"}]){const f=fixture();await assert.rejects(createActorLicense(body,f.deps),(e:unknown)=>e instanceof ActorLicenseError&&e.code==="VALIDATION");assert.equal(f.appends.length,0)}})
test("refuse le chevauchement et le numéro attribué à un autre acteur",async()=>{const existing={id_licence:"OLD",...payload,id_type_acteur:"TAC002",id_acteur:"COA1",id_cycle_licence:"CYC002",numero_licence:"OLD-N",id_statut_licence:"STL001"};await assert.rejects(createActorLicense(payload,fixture({ACTEURS_LICENCES:[existing]}).deps),(e:unknown)=>e instanceof ActorLicenseError&&e.code==="CHEVAUCHEMENT");await assert.rejects(createActorLicense({...payload,numero_licence:"OLD-N",id_type_acteur:"TAC003",id_acteur:"OFF1"},fixture({ACTEURS_LICENCES:[existing]}).deps),(e:unknown)=>e instanceof ActorLicenseError&&e.code==="NUMERO_DUPLIQUE")})
test("accepte des périodes successives et conserve les zéros du numéro",async()=>{const old={id_licence:"OLD",...payload,date_fin_validite:"2025-12-31",id_statut_licence:"STL002"},f=fixture({ACTEURS_LICENCES:[old]}),row=await createActorLicense(payload,f.deps);assert.equal(row.numero_licence,"001-A");assert.equal(f.appends.length,1)})
test("modifie la même ligne en gardant acteur et identifiant",async()=>{const old={id_licence:"OLD",...payload,id_statut_licence:"STL001"},f=fixture({ACTEURS_LICENCES:[old]});const row=await updateActorLicense("OLD",{...payload,id_acteur:"OFF1",numero_licence:"002"},f.deps);assert.equal(row.id_licence,"OLD");assert.equal(row.id_acteur,"COA1");assert.equal(f.upserts.length,1)})
test("refuse la réactivation expirée et annule sans supprimer",async()=>{const old={id_licence:"OLD",...payload,date_fin_validite:"2026-01-01",id_statut_licence:"STL003"},f=fixture({ACTEURS_LICENCES:[old]});await assert.rejects(updateActorLicenseStatus("OLD","reactivate","",f.deps,"2026-09-14"),/compatible/);await updateActorLicenseStatus("OLD","cancel","Motif",f.deps,"2026-09-14");assert.equal(f.upserts[0].rows[0].values.id_statut_licence,"STL005")})
test("enrichit la liste, les indicateurs et masque le cycle permanent du formulaire",async()=>{const f=fixture({ACTEURS_LICENCES:[{id_licence:"L1",...payload,id_statut_licence:"STL001"}]});const r=await listActorLicenses({},f.deps,"2026-06-01");assert.equal(r.licenses[0].actorName,"Coach Un");assert.equal(r.summary.valid,1);assert.equal(r.references.cycles.some(x=>x.label==="PERMANENT"),false)})
