import assert from "node:assert/strict";import test from "node:test";import { readFile } from "node:fs/promises";import { loadActivities,loadActivityDetail,saveActivity,saveActivityEntity,saveActivityParticipant } from "../lib/activities";import { loadDocuments,saveDocument,saveDocumentRelation } from "../lib/documents";import type { SheetRow } from "../lib/google-sheets"
const base:Record<string,SheetRow[]>={TYPES_ACTIVITE:[{id_type_activite:"TAC001",nom_type_activite:"REUNION"}],ROLES_ENTITE_ACTIVITE:[{id_role_entite_activite:"REA001",nom_role_entite_activite:"Invitée"}],TYPES_ACTEURS:[{id_type_acteur:"TYA001",nom_type_acteur:"ATHLETE",source_donnees:"ATHLETES"}],TYPES_DOCUMENT:[{id_type_document:"TDO001",nom_type_document:"PROCES VERBAL"}],LIGUES:[{id_ligue:"LIG1",nom_ligue:"Kinshasa"}],ENTENTES:[],CLUBS:[],EQUIPES:[],ATHLETES:[{id_athlete:"ATH1",nom_complet:"Alice"}],COACHS:[],ARBITRES:[],MEDECINS:[],OFFICIELS:[],AUTRES_ACTEURS:[],ACTIVITES:[{id_activite:"ACT0004",id_type_activite:"TAC001",id_entite_organisatrice:"LIG1",nom_activite:"Assemblée",date_debut:"2026-09-10",statut:"PLANIFIE"}],ACTIVITES_ENTITES:[],ACTIVITES_PARTICIPANTS:[],DOCUMENTS:[{id_document:"DOC0009",id_type_document:"TDO001",titre_document:"PV",statut:"ACTIF"}],DOCUMENTS_FICHIERS:[{id_fichier:"FIC0001",id_document:"DOC0009",nom_fichier:"pv.pdf",type_fichier:"application/pdf",id_fichier_drive:"drive",date_ajout:"2026-09-10"}],DOCUMENTS_RELATIONS:[]}
function fixture(overrides:Record<string,SheetRow[]>={}){const sheets={...base,...overrides},writes:unknown[]=[];return{deps:{readRows:async({sheet}:{sheet:string})=>sheets[sheet]||[],appendRows:async(arg:unknown)=>{writes.push(arg)},upsertRows:async(arg:unknown)=>{writes.push(arg)}} as never,writes}}
test("charge les activités et résout type et organisation",async()=>{const setup=fixture(),bundle=await loadActivities(setup.deps);assert.equal(bundle.activities[0].type,"REUNION");assert.equal(bundle.activities[0].organizer,"Kinshasa")})
test("crée ACT####, convertit les dates et refuse une période inversée",async()=>{const setup=fixture(),created=await saveActivity({id_type_activite:"TAC001",nom_activite:"Formation",date_debut:"12092026",date_fin:"13092026",statut:"PLANIFIE"},undefined,setup.deps);assert.equal("id" in created&&created.id,"ACT0005");assert.match(JSON.stringify(setup.writes),/2026-09-12/);const invalid=await saveActivity({id_type_activite:"TAC001",nom_activite:"X",date_debut:"13092026",date_fin:"12092026"},undefined,setup.deps);assert.ok("date_fin" in invalid.errors)})
test("ajoute une entité et un participant avec les en-têtes canoniques",async()=>{const setup=fixture();await saveActivityEntity("ACT0004",{id_entite:"LIG1",id_role_entite_activite:"REA001",statut_participation:"ACTIVE"},undefined,setup.deps);await saveActivityParticipant("ACT0004",{id_type_acteur:"TYA001",id_acteur:"ATH1",role_participation:"Invitée",statut_participation:"PRESENT"},undefined,setup.deps);const output=JSON.stringify(setup.writes);assert.match(output,/id_activite_entite/);assert.match(output,/id_participation/);assert.match(output,/role_participation/);assert.doesNotMatch(output,/role_participant/)})
test("charge le détail activité sans interface qualifications",async()=>{const setup=fixture({ACTIVITES_PARTICIPANTS:[{id_participation:"PAR0001",id_activite:"ACT0004",id_type_acteur:"TYA001",id_acteur:"ATH1"}]}),detail=await loadActivityDetail("ACT0004",setup.deps);assert.equal(detail?.participants[0].actor,"Alice");const source=await readFile("components/administration/activity-detail.tsx","utf8");assert.doesNotMatch(source,/qualification/i)})
test("charge les documents, tous leurs fichiers et génère DOC####",async()=>{const setup=fixture({DOCUMENTS_FICHIERS:[...base.DOCUMENTS_FICHIERS,{id_fichier:"FIC0002",id_document:"DOC0009",nom_fichier:"annexe.pdf"}]}),bundle=await loadDocuments(setup.deps);assert.equal(bundle.documents[0].fileCount,2);const created=await saveDocument({id_type_document:"TDO001",titre_document:"Courrier",date_document:"12092026",date_reception:"13092026"},undefined,setup.deps);assert.equal("id" in created&&created.id,"DOC0010")})
test("ajoute une relation document avec id_type_entite",async()=>{const setup=fixture();await saveDocumentRelation("DOC0009",{id_type_entite:"LIGUE",id_entite:"LIG1",type_relation:"CONCERNE"},undefined,setup.deps);assert.match(JSON.stringify(setup.writes),/id_type_entite/);assert.doesNotMatch(JSON.stringify(setup.writes),/id_type_entite_document/)})
test("les modules n’écrivent aucune ancienne colonne",async()=>{const sources=await Promise.all([readFile("lib/activities.ts","utf8"),readFile("lib/documents.ts","utf8")]),joined=sources.join("\n");for(const legacy of ["id_type_entite_organisatrice","id_ville","id_statut_activite","id_type_entite_activite","id_participation_activite","role_participant","date_expiration","version_document","BKB-ACT-","BKB-DOC-"])assert.doesNotMatch(joined,new RegExp(legacy))})
test("navigation, listes, erreurs et détails sont câblés",async()=>{const files=await Promise.all([readFile("components/dashboard/sidebar.tsx","utf8"),readFile("components/administration/activities-client.tsx","utf8"),readFile("components/administration/documents-client.tsx","utf8"),readFile("components/administration/document-detail.tsx","utf8")]),source=files.join("\n");assert.match(source,/Administration/);assert.match(source,/Données momentanément indisponibles/);assert.match(source,/Aucune donnée trouvée|Aucun fichier/);assert.match(source,/detailHref/);assert.match(source,/Fichiers/);assert.match(source,/Relations/)})
