import { z } from "zod"
import { appendSheetRowsAtomically, readSheetRows, upsertSheetRowsAtomically, type SheetRow } from "@/lib/google-sheets"
import { formatDateForSheet } from "@/lib/compact-date"

const clean=(value:unknown)=>String(value??"").trim().replace(/\s+/g," ")
export type ActivityOption={id:string;label:string;secondary?:string}
export type ActivityView={id:string;typeId:string;type:string;organizerId:string;organizer:string;name:string;publicTitle:string;summary:string;startDate:string;endDate:string;country:string;city:string;place:string;status:string;observations:string}
export type ActivityEntityView={id:string;entityId:string;entity:string;roleId:string;role:string;participationStatus:string;observations:string}
export type ActivityParticipantView={id:string;typeId:string;type:string;actorId:string;actor:string;participationRole:string;participationStatus:string;observations:string}
type Deps={readRows:typeof readSheetRows;appendRows:typeof appendSheetRowsAtomically;upsertRows:typeof upsertSheetRowsAtomically}
const defaults:Deps={readRows:readSheetRows,appendRows:appendSheetRowsAtomically,upsertRows:upsertSheetRowsAtomically}
const statusValues=["PLANIFIE","EN_COURS","TERMINE","REPORTE","ANNULE"] as const
const schema=z.object({id_type_activite:z.string().trim().min(1,"Le type est obligatoire."),id_entite_organisatrice:z.string().trim().optional().default(""),nom_activite:z.string().trim().min(1,"Le nom est obligatoire."),titre_public:z.string().trim().optional().default(""),resume:z.string().trim().optional().default(""),date_debut:z.string().trim().min(1,"La date de début est obligatoire."),date_fin:z.string().trim().optional().default(""),pays:z.string().trim().optional().default(""),ville:z.string().trim().optional().default(""),lieu:z.string().trim().optional().default(""),statut:z.enum(statusValues).default("PLANIFIE"),observations:z.string().trim().optional().default("")})
const option=(rows:SheetRow[],id:string,label:string,secondary?:string):ActivityOption[]=>rows.map(row=>({id:clean(row[id]),label:clean(row[label]),secondary})).filter(x=>x.id&&x.label)
const nextId=(ids:string[],prefix:string)=>`${prefix}${String(Math.max(0,...ids.map(id=>id.match(new RegExp(`^${prefix}(\\d{4})$`))?.[1]).filter(Boolean).map(Number))+1).padStart(4,"0")}`
const relationId=(ids:string[],prefix:string)=>`${prefix}${String(Math.max(0,...ids.map(id=>Number(id.replace(/^\D+/,""))).filter(Number.isFinite))+1).padStart(4,"0")}`

async function loadReferences(deps:Deps){
 const [types,roles,actorTypes,ligues,ententes,clubs,equipes,athletes,coachs,arbitres,medecins,officiels,autres]=await Promise.all([
  deps.readRows({block:"referentiel",sheet:"TYPES_ACTIVITE",range:"A:D"}),deps.readRows({block:"referentiel",sheet:"ROLES_ENTITE_ACTIVITE",range:"A:C"}),deps.readRows({block:"referentiel",sheet:"TYPES_ACTEURS",range:"A:Z"}),
  deps.readRows({block:"structure",sheet:"LIGUES",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"ENTENTES",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"CLUBS",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"EQUIPES",range:"A:ZZ"}),
  deps.readRows({block:"acteurs",sheet:"ATHLETES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"COACHS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"ARBITRES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"MEDECINS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"OFFICIELS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"AUTRES",range:"A:ZZ"}),
 ])
 const entities=[...option(ligues,"id_ligue","nom_ligue","Ligue"),...option(ententes,"id_entente","nom_entente","Entente"),...option(clubs,"id_club","nom_club","Club"),...option(equipes,"id_equipe","nom_equipe","Équipe")]
 const sources:Record<string,{rows:SheetRow[];id:string}>={ATHLETES:{rows:athletes,id:"id_athlete"},COACHS:{rows:coachs,id:"id_coach"},ARBITRES:{rows:arbitres,id:"id_arbitre"},MEDECINS:{rows:medecins,id:"id_medecin"},OFFICIELS:{rows:officiels,id:"id_officiel"},AUTRES:{rows:autres,id:"id_autre_acteur"},AUTRES_ACTEURS:{rows:autres,id:"id_autre_acteur"}}
 const typeOptions=option(actorTypes,"id_type_acteur","nom_type_acteur"),actorsByType=Object.fromEntries(typeOptions.map(type=>{const row=actorTypes.find(x=>clean(x.id_type_acteur)===type.id),source=sources[clean(row?.source_donnees)];return[type.id,source?option(source.rows,source.id,"nom_complet"):[]]}))
 return{types:option(types,"id_type_activite","nom_type_activite"),roles:option(roles,"id_role_entite_activite","nom_role_entite_activite"),actorTypes:typeOptions,actorsByType,entities}
}
export async function loadActivities(deps:Deps=defaults){const[rows,references]=await Promise.all([deps.readRows({block:"activities",sheet:"ACTIVITES",range:"A:M"}),loadReferences(deps)]),types=new Map(references.types.map(x=>[x.id,x.label])),entities=new Map(references.entities.map(x=>[x.id,x.label]));const activities:ActivityView[]=rows.map(row=>({id:clean(row.id_activite),typeId:clean(row.id_type_activite),type:types.get(clean(row.id_type_activite))||"Type non reconnu",organizerId:clean(row.id_entite_organisatrice),organizer:entities.get(clean(row.id_entite_organisatrice))||clean(row.id_entite_organisatrice),name:clean(row.nom_activite),publicTitle:clean(row.titre_public),summary:clean(row.resume),startDate:clean(row.date_debut),endDate:clean(row.date_fin),country:clean(row.pays),city:clean(row.ville),place:clean(row.lieu),status:clean(row.statut),observations:clean(row.observations)})).filter(x=>x.id);return{activities,references}}
export async function loadActivityDetail(id:string,deps:Deps=defaults){const[bundle,entityRows,participantRows]=await Promise.all([loadActivities(deps),deps.readRows({block:"activities",sheet:"ACTIVITES_ENTITES",range:"A:F"}),deps.readRows({block:"activities",sheet:"ACTIVITES_PARTICIPANTS",range:"A:G"})]),activity=bundle.activities.find(x=>x.id===id);if(!activity)return undefined;const entityLabels=new Map(bundle.references.entities.map(x=>[x.id,x.label])),roleLabels=new Map(bundle.references.roles.map(x=>[x.id,x.label])),typeLabels=new Map(bundle.references.actorTypes.map(x=>[x.id,x.label]));const actorLabels=new Map(Object.values(bundle.references.actorsByType).flat().map(x=>[x.id,x.label]));return{activity,references:bundle.references,entities:entityRows.filter(x=>clean(x.id_activite)===id).map(x=>({id:clean(x.id_activite_entite),entityId:clean(x.id_entite),entity:entityLabels.get(clean(x.id_entite))||clean(x.id_entite),roleId:clean(x.id_role_entite_activite),role:roleLabels.get(clean(x.id_role_entite_activite))||clean(x.id_role_entite_activite),participationStatus:clean(x.statut_participation),observations:clean(x.observations)})),participants:participantRows.filter(x=>clean(x.id_activite)===id).map(x=>({id:clean(x.id_participation),typeId:clean(x.id_type_acteur),type:typeLabels.get(clean(x.id_type_acteur))||clean(x.id_type_acteur),actorId:clean(x.id_acteur),actor:actorLabels.get(clean(x.id_acteur))||clean(x.id_acteur),participationRole:clean(x.role_participation),participationStatus:clean(x.statut_participation),observations:clean(x.observations)}))}}
function parseInput(input:unknown){const result=schema.safeParse(input);if(!result.success)return{errors:Object.fromEntries(result.error.issues.map(x=>[String(x.path[0]||"_form"),x.message]))};const values=result.data;try{values.date_debut=formatDateForSheet(values.date_debut);values.date_fin=values.date_fin?formatDateForSheet(values.date_fin):""}catch{return{errors:{date_debut:"Saisissez une date civile valide (JJMMAAAA)."}}}if(values.date_fin&&values.date_fin<values.date_debut)return{errors:{date_fin:"La date de fin ne peut pas précéder la date de début."}};return{values,errors:{}}}
export async function saveActivity(input:unknown,id?:string,deps:Deps=defaults){const parsed=parseInput(input);if(!parsed.values)return parsed;const bundle=await loadActivities(deps);if(!bundle.references.types.some(x=>x.id===parsed.values.id_type_activite))return{errors:{id_type_activite:"Type inconnu."}};if(parsed.values.id_entite_organisatrice&&!bundle.references.entities.some(x=>x.id===parsed.values.id_entite_organisatrice))return{errors:{id_entite_organisatrice:"Entité organisatrice inconnue."}};const activityId=id||nextId(bundle.activities.map(x=>x.id),"ACT");await deps.upsertRows({block:"activities",rows:[{sheet:"ACTIVITES",idHeader:"id_activite",values:{id_activite:activityId,...parsed.values}}]});return{id:activityId,errors:{}}}
export async function saveActivityEntity(activityId:string,input:Record<string,unknown>,id:string|undefined,deps:Deps=defaults){const detail=await loadActivityDetail(activityId,deps);if(!detail)throw new Error("Activité introuvable.");const entityId=clean(input.id_entite),roleId=clean(input.id_role_entite_activite);if(!detail.references.entities.some(x=>x.id===entityId)||!detail.references.roles.some(x=>x.id===roleId))throw new Error("Entité ou rôle invalide.");const rowId=id||relationId(detail.entities.map(x=>x.id),"AEN");await deps.upsertRows({block:"activities",rows:[{sheet:"ACTIVITES_ENTITES",idHeader:"id_activite_entite",values:{id_activite_entite:rowId,id_activite:activityId,id_entite:entityId,id_role_entite_activite:roleId,statut_participation:clean(input.statut_participation)||"ACTIF",observations:clean(input.observations)}}]});return{rowId}}
export async function saveActivityParticipant(activityId:string,input:Record<string,unknown>,id:string|undefined,deps:Deps=defaults){const detail=await loadActivityDetail(activityId,deps);if(!detail)throw new Error("Activité introuvable.");const typeId=clean(input.id_type_acteur),actorId=clean(input.id_acteur);if(!detail.references.actorsByType[typeId]?.some(x=>x.id===actorId))throw new Error("Participant ou type d’acteur invalide.");const rowId=id||relationId(detail.participants.map(x=>x.id),"PAR");await deps.upsertRows({block:"activities",rows:[{sheet:"ACTIVITES_PARTICIPANTS",idHeader:"id_participation",values:{id_participation:rowId,id_activite:activityId,id_type_acteur:typeId,id_acteur:actorId,role_participation:clean(input.role_participation),statut_participation:clean(input.statut_participation)||"ACTIF",observations:clean(input.observations)}}]});return{rowId}}
export { statusValues as activityStatuses }
