import { appendSheetRowsAtomically, pickFirst, readSheetRows, upsertSheetRowsAtomically, type SheetRow } from "@/lib/google-sheets"

const clean=(v:unknown)=>String(v??"").trim()
const iso=/^\d{4}-\d{2}-\d{2}$/
export const ACTOR_LICENSE_TYPES={TAC002:{label:"Coach",sheet:"COACHS",id:"id_coach",route:"coachs"},TAC003:{label:"Officiel",sheet:"OFFICIELS",id:"id_officiel",route:"officiels"},TAC004:{label:"Arbitre",sheet:"ARBITRES",id:"id_arbitre",route:"arbitres"},TAC005:{label:"Médecin",sheet:"MEDECINS",id:"id_medecin",route:"medecins"}} as const
export type ActorLicenseType=keyof typeof ACTOR_LICENSE_TYPES
export class ActorLicenseError extends Error{constructor(public code:string,message:string,public status=400,public fields:Record<string,string>={}){super(message)}}
type Deps={readRows:typeof readSheetRows;appendRows:typeof appendSheetRowsAtomically;upsertRows:typeof upsertSheetRowsAtomically}
const defaults:Deps={readRows:readSheetRows,appendRows:appendSheetRowsAtomically,upsertRows:upsertSheetRowsAtomically}

async function load(deps:Deps){const [licenses,types,cycles,statuses,coachs,officiels,arbitres,medecins]=await Promise.all([
 deps.readRows({block:"licences",sheet:"ACTEURS_LICENCES",range:"A:J"}),deps.readRows({block:"referentiel",sheet:"TYPES_ACTEURS",range:"A:E"}),deps.readRows({block:"referentiel",sheet:"CYCLES_LICENCES",range:"A:D"}),deps.readRows({block:"referentiel",sheet:"STATUT_LICENCE",range:"A:D"}),
 deps.readRows({block:"acteurs",sheet:"COACHS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"OFFICIELS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"ARBITRES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"MEDECINS",range:"A:ZZ"})]);return{licenses,types,cycles,statuses,actors:{TAC002:coachs,TAC003:officiels,TAC004:arbitres,TAC005:medecins}}}
const labelMap=(rows:SheetRow[],id:string,label:string)=>new Map(rows.map(r=>[clean(r[id]),clean(r[label])||clean(r[id])]))
const actorName=(row:SheetRow|undefined,id:string)=>clean(row?.nom_complet)||[row?.nom,row?.postnom,row?.prenom].map(clean).filter(Boolean).join(" ")||id

export type EffectiveActorLicenseStatus="VALIDE"|"A_VENIR"|"EXPIREE"|"SUSPENDUE"|"CLOTUREE"|"ANNULEE"|string
export function getEffectiveLicenseStatus(status:string,start:string,end:string,today=new Date().toISOString().slice(0,10)):EffectiveActorLicenseStatus{const s=clean(status).normalize("NFD").replace(/\p{Diacritic}/gu,"").toUpperCase();if(["SUSPENDUE","CLOTUREE","ANNULEE"].includes(s))return s;if(s!=="ACTIVE")return s||"NON_DEFINI";if(start>today)return"A_VENIR";if(end<today)return"EXPIREE";return"VALIDE"}
export const daysBetween=(from:string,to:string)=>Math.round((Date.UTC(+to.slice(0,4),+to.slice(5,7)-1,+to.slice(8,10))-Date.UTC(+from.slice(0,4),+from.slice(5,7)-1,+from.slice(8,10)))/86400000)
export function checkActorLicenseOverlap(rows:SheetRow[],typeId:string,actorId:string,start:string,end:string,excludeId=""){return rows.find(r=>clean(r.id_licence)!==excludeId&&clean(r.id_type_acteur)===typeId&&clean(r.id_acteur)===actorId&&!(["STL004","STL005"].includes(clean(r.id_statut_licence)))&&start<=clean(r.date_fin_validite)&&end>=clean(r.date_debut_validite))}
export function generateActorLicenseId(delivery:string,rows:SheetRow[]){const year=delivery.slice(0,4),pattern=new RegExp(`^BKB-ACL-${year}-(\\d{6})$`),n=Math.max(0,...rows.map(r=>clean(r.id_licence).match(pattern)).filter((m):m is RegExpMatchArray=>!!m).map(m=>+m[1]));return`BKB-ACL-${year}-${String(n+1).padStart(6,"0")}`}

function maps(data:Awaited<ReturnType<typeof load>>){return{types:labelMap(data.types,"id_type_acteur","nom_type_acteur"),cycles:labelMap(data.cycles,"id_cycle_licence","nom_cycle_licence"),statuses:labelMap(data.statuses,"id_statut_licence","nom_statut_licence")}}
function view(row:SheetRow,data:Awaited<ReturnType<typeof load>>,today:string){const m=maps(data),typeId=clean(row.id_type_acteur) as ActorLicenseType,config=ACTOR_LICENSE_TYPES[typeId],actorId=clean(row.id_acteur),actor=config?data.actors[typeId].find(r=>clean(r[config.id])===actorId):undefined,statusId=clean(row.id_statut_licence),status=m.statuses.get(statusId)||statusId,start=clean(row.date_debut_validite),end=clean(row.date_fin_validite),effectiveStatus=getEffectiveLicenseStatus(status,start,end,today),remaining=end&&iso.test(end)?daysBetween(today,end):null;return{__key:clean(row.id_licence),id:clean(row.id_licence),typeId,type:m.types.get(typeId)||config?.label||typeId,actorId,actorName:actorName(actor,actorId),actorRoute:config?.route||"",avatarUrl:clean(actor?.avatar_drive_url),cycleId:clean(row.id_cycle_licence),cycle:m.cycles.get(clean(row.id_cycle_licence))||clean(row.id_cycle_licence),number:clean(row.numero_licence),deliveryDate:clean(row.date_delivrance),validFrom:start,validUntil:end,statusId,status,effectiveStatus,observations:clean(row.observations),remainingDays:remaining}}
export type ActorLicenseView=ReturnType<typeof view>

export async function listActorLicenses(filters:{search?:string;typeId?:string;status?:string;cycleId?:string;deliveryFrom?:string;deliveryTo?:string;expiryFrom?:string;expiryTo?:string;dueDays?:number}={},deps:Deps=defaults,today=new Date().toISOString().slice(0,10)){const data=await load(deps),q=clean(filters.search).toLocaleLowerCase("fr"),licenses=data.licenses.map(r=>view(r,data,today)).filter(x=>!q||`${x.id} ${x.number} ${x.actorId} ${x.actorName}`.toLocaleLowerCase("fr").includes(q)).filter(x=>!filters.typeId||x.typeId===filters.typeId).filter(x=>!filters.status||x.effectiveStatus===filters.status).filter(x=>!filters.cycleId||x.cycleId===filters.cycleId).filter(x=>!filters.deliveryFrom||x.deliveryDate>=filters.deliveryFrom).filter(x=>!filters.deliveryTo||x.deliveryDate<=filters.deliveryTo).filter(x=>!filters.expiryFrom||x.validUntil>=filters.expiryFrom).filter(x=>!filters.expiryTo||x.validUntil<=filters.expiryTo).filter(x=>filters.dueDays===undefined||x.remainingDays!==null&&x.remainingDays>=0&&x.remainingDays<=filters.dueDays).sort((a,b)=>b.deliveryDate.localeCompare(a.deliveryDate)||b.id.localeCompare(a.id)),summary={total:licenses.length,valid:licenses.filter(x=>x.effectiveStatus==="VALIDE").length,upcoming:licenses.filter(x=>x.effectiveStatus==="A_VENIR").length,expired:licenses.filter(x=>x.effectiveStatus==="EXPIREE").length,suspended:licenses.filter(x=>x.effectiveStatus==="SUSPENDUE").length,due30:licenses.filter(x=>x.effectiveStatus==="VALIDE"&&x.remainingDays!==null&&x.remainingDays>=0&&x.remainingDays<=30).length},byType=Object.entries(ACTOR_LICENSE_TYPES).map(([id,c])=>({id,label:c.label,total:licenses.filter(x=>x.typeId===id).length})),expirations=[{label:"0 à 30 jours",from:0,to:30},{label:"31 à 60 jours",from:31,to:60},{label:"61 à 90 jours",from:61,to:90}].map(bucket=>({...bucket,licenses:licenses.filter(x=>x.effectiveStatus==="VALIDE"&&x.remainingDays!==null&&x.remainingDays>=bucket.from&&x.remainingDays<=bucket.to)}));const actorOptions=Object.entries(ACTOR_LICENSE_TYPES).flatMap(([typeId,c])=>data.actors[typeId as ActorLicenseType].map(r=>({id:clean(r[c.id]),label:actorName(r,clean(r[c.id])),typeId,status:clean(r.statut)})).filter(x=>x.id));return{licenses,summary,byType,expirations,references:{types:Object.entries(ACTOR_LICENSE_TYPES).map(([id,c])=>({id,label:c.label})),cycles:data.cycles.filter(r=>clean(r.nom_cycle_licence).toUpperCase()!=="PERMANENT").map(r=>({id:clean(r.id_cycle_licence),label:clean(r.nom_cycle_licence)})).filter(x=>x.id),statuses:data.statuses.map(r=>({id:clean(r.id_statut_licence),label:clean(r.nom_statut_licence)})).filter(x=>x.id),actors:actorOptions}}}

function source(body:unknown){return body&&typeof body==="object"?body as Record<string,unknown>:{} }
function validate(input:Record<string,unknown>,data:Awaited<ReturnType<typeof load>>){const fields:Record<string,string>={},typeId=clean(input.id_type_acteur) as ActorLicenseType,actorId=clean(input.id_acteur),cycleId=clean(input.id_cycle_licence),number=clean(input.numero_licence),delivery=clean(input.date_delivrance),start=clean(input.date_debut_validite),end=clean(input.date_fin_validite),config=ACTOR_LICENSE_TYPES[typeId];if(!config)fields.id_type_acteur="Type d’acteur non autorisé.";else if(!data.actors[typeId].some(r=>clean(r[config.id])===actorId))fields.id_acteur="Acteur introuvable pour ce type.";const cycle=data.cycles.find(r=>clean(r.id_cycle_licence)===cycleId);if(!cycle||clean(cycle.nom_cycle_licence).toUpperCase()==="PERMANENT")fields.id_cycle_licence="Cycle indisponible pour ce module.";if(!number)fields.numero_licence="Le numéro officiel est obligatoire.";for(const [key,v] of [["date_delivrance",delivery],["date_debut_validite",start],["date_fin_validite",end]])if(!iso.test(v))fields[key]="Date obligatoire au format YYYY-MM-DD.";if(iso.test(delivery)&&iso.test(start)&&delivery>start)fields.date_delivrance="La délivrance ne peut pas être postérieure au début.";if(iso.test(start)&&iso.test(end)&&start>end)fields.date_fin_validite="L’expiration doit être postérieure ou égale au début.";if(cycleId==="CYC099"&&!clean(input.observations))fields.observations="Une précision est obligatoire pour le cycle AUTRE.";if(Object.keys(fields).length)throw new ActorLicenseError("VALIDATION","Veuillez corriger les champs indiqués.",422,fields);return{typeId,actorId,cycleId,number,delivery,start,end,observations:clean(input.observations)}}
function prepareFromData(body:unknown,data:Awaited<ReturnType<typeof load>>,excludeId=""){const input=source(body),v=validate(input,data),duplicate=data.licenses.find(r=>clean(r.id_licence)!==excludeId&&clean(r.numero_licence)===v.number&&!(clean(r.id_type_acteur)===v.typeId&&clean(r.id_acteur)===v.actorId));if(duplicate)throw new ActorLicenseError("NUMERO_DUPLIQUE",`Ce numéro est déjà associé à la licence ${clean(duplicate.id_licence)}.`,409,{numero_licence:"Numéro déjà utilisé par un autre acteur."});const overlap=checkActorLicenseOverlap(data.licenses,v.typeId,v.actorId,v.start,v.end,excludeId);if(overlap)throw new ActorLicenseError("CHEVAUCHEMENT",`Cette période chevauche déjà la licence ${clean(overlap.id_licence)} valable du ${clean(overlap.date_debut_validite)} au ${clean(overlap.date_fin_validite)}.`,409,{date_debut_validite:"Période déjà couverte.",date_fin_validite:"Période déjà couverte."});return{data,v}}
async function prepare(body:unknown,deps:Deps,excludeId=""){return prepareFromData(body,await load(deps),excludeId)}
export async function createActorLicense(body:unknown,deps:Deps=defaults){const{data,v}=await prepare(body,deps),active=data.statuses.find(r=>clean(r.nom_statut_licence).toUpperCase()==="ACTIVE");if(!active)throw new ActorLicenseError("REFERENTIEL_INCOMPLET","Le statut ACTIVE est introuvable.",503);const row={id_licence:generateActorLicenseId(v.delivery,data.licenses),id_type_acteur:v.typeId,id_acteur:v.actorId,id_cycle_licence:v.cycleId,numero_licence:v.number,date_delivrance:v.delivery,date_debut_validite:v.start,date_fin_validite:v.end,id_statut_licence:clean(active.id_statut_licence),observations:v.observations};await deps.appendRows({block:"licences",rows:[{sheet:"ACTEURS_LICENCES",values:row}]});return row}
export async function updateActorLicense(id:string,body:unknown,deps:Deps=defaults){const data=await load(deps),current=data.licenses.filter(r=>clean(r.id_licence)===clean(id));if(current.length!==1)throw new ActorLicenseError(current.length?"IDENTIFIANT_AMBIGU":"LICENCE_INTROUVABLE","Licence introuvable ou identifiant non unique.",current.length?409:404);const merged={...current[0],...source(body),id_type_acteur:current[0].id_type_acteur,id_acteur:current[0].id_acteur},prepared=prepareFromData(merged,data,clean(id)),row={...current[0],id_licence:clean(id),id_type_acteur:prepared.v.typeId,id_acteur:prepared.v.actorId,id_cycle_licence:prepared.v.cycleId,numero_licence:prepared.v.number,date_delivrance:prepared.v.delivery,date_debut_validite:prepared.v.start,date_fin_validite:prepared.v.end,id_statut_licence:clean(current[0].id_statut_licence),observations:prepared.v.observations};await deps.upsertRows({block:"licences",rows:[{sheet:"ACTEURS_LICENCES",idHeader:"id_licence",values:row}]});return row}
export async function updateActorLicenseStatus(id:string,action:"suspend"|"reactivate"|"close"|"cancel",observations="",deps:Deps=defaults,today=new Date().toISOString().slice(0,10)){const data=await load(deps),rows=data.licenses.filter(r=>clean(r.id_licence)===clean(id));if(rows.length!==1)throw new ActorLicenseError("LICENCE_INTROUVABLE","Licence introuvable.",404);const row=rows[0],m=maps(data),effective=getEffectiveLicenseStatus(m.statuses.get(clean(row.id_statut_licence))||"",clean(row.date_debut_validite),clean(row.date_fin_validite),today),allowed:Record<typeof action,string[]>={suspend:["VALIDE","A_VENIR"],reactivate:["SUSPENDUE"],close:["VALIDE","A_VENIR","SUSPENDUE"],cancel:["VALIDE","A_VENIR","SUSPENDUE","EXPIREE","CLOTUREE"]};if(!allowed[action].includes(effective)||action==="reactivate"&&clean(row.date_fin_validite)<today)throw new ActorLicenseError("ACTION_INTERDITE","Cette action n’est pas compatible avec l’état de la licence.",409);const wanted={suspend:"SUSPENDUE",reactivate:"ACTIVE",close:"CLOTUREE",cancel:"ANNULEE"}[action],status=data.statuses.find(r=>clean(r.nom_statut_licence).normalize("NFD").replace(/\p{Diacritic}/gu,"").toUpperCase()===wanted);if(!status)throw new ActorLicenseError("REFERENTIEL_INCOMPLET",`Le statut ${wanted} est introuvable.`,503);const values={...row,id_statut_licence:clean(status.id_statut_licence),observations:clean(observations)||clean(row.observations)};await deps.upsertRows({block:"licences",rows:[{sheet:"ACTEURS_LICENCES",idHeader:"id_licence",values}]});return values}
