import { z } from "zod"
import { appendSheetRowsAtomically, readSheetRows, upsertSheetRowsAtomically, type SheetRow } from "@/lib/google-sheets"
import { formatDateForSheet } from "@/lib/compact-date"
import { rollbackDocumentFile, uploadDocumentFile } from "@/lib/google-document-file"

const clean=(value:unknown)=>String(value??"").trim().replace(/\s+/g," ")
export type DocumentOption={id:string;label:string;typeId?:string;secondary?:string}
export type DocumentFileView={id:string;documentId:string;name:string;type:string;url:string;driveId:string;addedDate:string;observations:string}
export type DocumentRelationView={id:string;documentId:string;entityTypeId:string;entityType:string;entityId:string;entity:string;relationType:string;observations:string}
export type DocumentView={id:string;typeId:string;type:string;title:string;reference:string;documentDate:string;receptionDate:string;description:string;status:string;observations:string;files:DocumentFileView[];relations:DocumentRelationView[];fileCount:number}
type Deps={readRows:typeof readSheetRows;appendRows:typeof appendSheetRowsAtomically;upsertRows:typeof upsertSheetRowsAtomically}
const defaults:Deps={readRows:readSheetRows,appendRows:appendSheetRowsAtomically,upsertRows:upsertSheetRowsAtomically}
const statuses=["ACTIF","ARCHIVE","BROUILLON"] as const
const schema=z.object({id_type_document:z.string().trim().min(1,"Le type est obligatoire."),titre_document:z.string().trim().min(1,"Le titre est obligatoire."),numero_reference:z.string().trim().optional().default(""),date_document:z.string().trim().optional().default(""),date_reception:z.string().trim().optional().default(""),description:z.string().trim().optional().default(""),statut:z.enum(statuses).default("ACTIF"),observations:z.string().trim().optional().default("")})
const option=(rows:SheetRow[],id:string,label:string,typeId?:string,secondary?:string):DocumentOption[]=>rows.map(row=>({id:clean(row[id]),label:clean(row[label]),typeId,secondary})).filter(x=>x.id&&x.label)
const nextId=(ids:string[],prefix:string)=>`${prefix}${String(Math.max(0,...ids.map(id=>id.match(new RegExp(`^${prefix}(\\d{4})$`))?.[1]).filter(Boolean).map(Number))+1).padStart(4,"0")}`
const secondaryId=(ids:string[],prefix:string)=>`${prefix}${String(Math.max(0,...ids.map(id=>Number(id.replace(/^\D+/,""))).filter(Number.isFinite))+1).padStart(4,"0")}`
async function refs(deps:Deps){const[types,actorTypes,ligues,ententes,clubs,equipes,athletes,coachs,arbitres,medecins,officiels,autres]=await Promise.all([deps.readRows({block:"referentiel",sheet:"TYPES_DOCUMENT",range:"A:C"}),deps.readRows({block:"referentiel",sheet:"TYPES_ACTEURS",range:"A:Z"}),deps.readRows({block:"structure",sheet:"LIGUES",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"ENTENTES",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"CLUBS",range:"A:ZZ"}),deps.readRows({block:"structure",sheet:"EQUIPES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"ATHLETES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"COACHS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"ARBITRES",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"MEDECINS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"OFFICIELS",range:"A:ZZ"}),deps.readRows({block:"acteurs",sheet:"AUTRES",range:"A:ZZ"})]);const entities=[...option(ligues,"id_ligue","nom_ligue","LIGUE","Ligue"),...option(ententes,"id_entente","nom_entente","ENTENTE","Entente"),...option(clubs,"id_club","nom_club","CLUB","Club"),...option(equipes,"id_equipe","nom_equipe","EQUIPE","Équipe")];const sourceRows:Record<string,{rows:SheetRow[];id:string}>={ATHLETES:{rows:athletes,id:"id_athlete"},COACHS:{rows:coachs,id:"id_coach"},ARBITRES:{rows:arbitres,id:"id_arbitre"},MEDECINS:{rows:medecins,id:"id_medecin"},OFFICIELS:{rows:officiels,id:"id_officiel"},AUTRES:{rows:autres,id:"id_autre_acteur"},AUTRES_ACTEURS:{rows:autres,id:"id_autre_acteur"}};for(const type of actorTypes){const source=sourceRows[clean(type.source_donnees)];if(source)entities.push(...option(source.rows,source.id,"nom_complet",clean(type.id_type_acteur),clean(type.nom_type_acteur)))}return{types:option(types,"id_type_document","nom_type_document"),entities}}
export async function loadDocuments(deps:Deps=defaults){const[documents,files,relations,references]=await Promise.all([deps.readRows({block:"documents",sheet:"DOCUMENTS",range:"A:I"}),deps.readRows({block:"documents",sheet:"DOCUMENTS_FICHIERS",range:"A:H"}),deps.readRows({block:"documents",sheet:"DOCUMENTS_RELATIONS",range:"A:F"}),refs(deps)]),typeMap=new Map(references.types.map(x=>[x.id,x.label])),entityMap=new Map(references.entities.map(x=>[`${x.typeId}:${x.id}`,x.label]));const fileViews:DocumentFileView[]=files.map(x=>({id:clean(x.id_fichier),documentId:clean(x.id_document),name:clean(x.nom_fichier),type:clean(x.type_fichier),url:clean(x.url_fichier),driveId:clean(x.id_fichier_drive),addedDate:clean(x.date_ajout),observations:clean(x.observations)})).filter(x=>x.id);const relationViews:DocumentRelationView[]=relations.map(x=>{const typeId=clean(x.id_type_entite),entityId=clean(x.id_entite);return{id:clean(x.id_relation_document),documentId:clean(x.id_document),entityTypeId:typeId,entityType:references.entities.find(e=>e.typeId===typeId)?.secondary||typeId,entityId,entity:entityMap.get(`${typeId}:${entityId}`)||entityId,relationType:clean(x.type_relation),observations:clean(x.observations)}}).filter(x=>x.id);const items:DocumentView[]=documents.map(x=>{const id=clean(x.id_document),typeId=clean(x.id_type_document),ownFiles=fileViews.filter(f=>f.documentId===id),ownRelations=relationViews.filter(r=>r.documentId===id);return{id,typeId,type:typeMap.get(typeId)||"Type non reconnu",title:clean(x.titre_document),reference:clean(x.numero_reference),documentDate:clean(x.date_document),receptionDate:clean(x.date_reception),description:clean(x.description),status:clean(x.statut),observations:clean(x.observations),files:ownFiles,relations:ownRelations,fileCount:ownFiles.length}}).filter(x=>x.id);return{documents:items,references}}
function parse(input:unknown){const result=schema.safeParse(input);if(!result.success)return{errors:Object.fromEntries(result.error.issues.map(x=>[String(x.path[0]||"_form"),x.message]))};const values=result.data;try{values.date_document=values.date_document?formatDateForSheet(values.date_document):"";values.date_reception=values.date_reception?formatDateForSheet(values.date_reception):""}catch{return{errors:{date_document:"Saisissez une date civile valide (JJMMAAAA)."}}}if(values.date_document&&values.date_reception&&values.date_reception<values.date_document)return{errors:{date_reception:"La réception ne peut pas précéder la date du document."}};return{values,errors:{}}}
export async function saveDocument(input:unknown,id?:string,deps:Deps=defaults){const parsed=parse(input);if(!parsed.values)return parsed;const bundle=await loadDocuments(deps);if(!bundle.references.types.some(x=>x.id===parsed.values.id_type_document))return{errors:{id_type_document:"Type inconnu."}};const documentId=id||nextId(bundle.documents.map(x=>x.id),"DOC");await deps.upsertRows({block:"documents",rows:[{sheet:"DOCUMENTS",idHeader:"id_document",values:{id_document:documentId,...parsed.values}}]});return{id:documentId,errors:{}}}
export async function addDocumentFile(documentId:string,file:File,observations="",deps:Deps=defaults){const bundle=await loadDocuments(deps);if(!bundle.documents.some(x=>x.id===documentId))throw new Error("Document introuvable.");const uploaded=await uploadDocumentFile(documentId,bundle.documents.find(x=>x.id===documentId)!.title,file),id=secondaryId(bundle.documents.flatMap(x=>x.files.map(f=>f.id)),"FIC");try{await deps.appendRows({block:"documents",rows:[{sheet:"DOCUMENTS_FICHIERS",values:{id_fichier:id,id_document:documentId,nom_fichier:uploaded.name,type_fichier:uploaded.mimeType,url_fichier:uploaded.url,id_fichier_drive:uploaded.id,date_ajout:new Date().toISOString().slice(0,10),observations:clean(observations)}}]})}catch(error){await rollbackDocumentFile(uploaded.id).catch(()=>undefined);throw error}return{id}}
export async function saveDocumentRelation(documentId:string,input:Record<string,unknown>,id:string|undefined,deps:Deps=defaults){const bundle=await loadDocuments(deps),entityTypeId=clean(input.id_type_entite),entityId=clean(input.id_entite);if(!bundle.documents.some(x=>x.id===documentId))throw new Error("Document introuvable.");if(!bundle.references.entities.some(x=>x.typeId===entityTypeId&&x.id===entityId))throw new Error("Relation vers une entité inconnue.");const rowId=id||secondaryId(bundle.documents.flatMap(x=>x.relations.map(r=>r.id)),"RDO");await deps.upsertRows({block:"documents",rows:[{sheet:"DOCUMENTS_RELATIONS",idHeader:"id_relation_document",values:{id_relation_document:rowId,id_document:documentId,id_type_entite:entityTypeId,id_entite:entityId,type_relation:clean(input.type_relation)||"CONCERNE",observations:clean(input.observations)}}]});return{id:rowId}}
export { statuses as documentStatuses }
