import { pickFirst, readSheetRows, writeSheetRowByHeaders, type SheetRow } from "@/lib/google-sheets"
import { assertCampaignTransition, assertDates, generateNationalId, normalizeEngagementRow, sequenceFromId } from "@/lib/national-teams-domain"

const sheets = { teams:"EQUIPES_NATIONALES", seasons:"EQUIPES_NATIONALES_SAISONS", campaigns:"CAMPAGNES_EQUIPES_NATIONALES", selections:"SELECTIONS_ATHLETES", staff:"AFFECTATIONS_STAFF", engagements:"ENGAGEMENTS_EQUIPE_NATIONALE" } as const
const clean=(v:unknown)=>String(v??"").trim()
const label=(r?:SheetRow)=>r ? pickFirst(r,["nom_complet","nom_equipe_nationale","nom_competition","nom_epreuve","nom_discipline","nom_categorie_age","nom_sexe","nom_saison","nom_statut_campagne","nom_statut_selection","nom_statut_engagement","nom_poste","nom_fonction","libelle","nom"])||[r.prenom,r.nom].filter(Boolean).join(" ") : ""
const rows=(sheet:string,fresh=false)=>readSheetRows({block:"equipeNationale",sheet,range:"A:ZZ",fresh})
const refs=(sheet:string)=>readSheetRows({block:"referentiel",sheet,range:"A:ZZ"})
export class NationalTeamError extends Error { constructor(public code:string,message:string,public status=422,public fields?:Record<string,string>){super(message)} }
const required=(body:Record<string,string>, names:string[])=>{const errors:Record<string,string>={};for(const n of names)if(!clean(body[n]))errors[n]="Ce champ est obligatoire.";if(Object.keys(errors).length)throw new NationalTeamError("CHAMPS_INVALIDES","Vérifiez les champs obligatoires.",422,errors)}

async function loadCore(fresh=false){const [teams,seasons,campaigns,selections,staff,engagements]=await Promise.all(Object.values(sheets).map(s=>rows(s,fresh)));return{teams,seasons,campaigns,selections,staff,engagements:engagements.map(normalizeEngagementRow)}}
export async function getNationalTeamsDashboard(){
 const [d,disciplines,categories,sexes,seasonRefs,campaignStatuses,selectionStatuses,engagementStatuses,posts,functions,competitions,events,units,matches,results,athletes,athleteAffiliations,coaches,officials,referees,doctors,actorTypes]=await Promise.all([loadCore(),refs("DISCIPLINES"),refs("CATEGORIES_AGE"),refs("SEXES"),refs("SAISON"),refs("STATUTS_CAMPAGNES_EN"),refs("STATUTS_SELECTIONS_EN"),refs("STATUTS_ENGAGEMENTS_EN"),refs("POSTES_BASKETBALL"),refs("FONCTIONS"),readSheetRows({block:"competitions",sheet:"COMPETITIONS"}),readSheetRows({block:"competitions",sheet:"COMPETITIONS_EPREUVES"}),readSheetRows({block:"competitions",sheet:"COMPETITIONS_UNITES"}),readSheetRows({block:"competitions",sheet:"COMPETITIONS_MATCHS"}),readSheetRows({block:"competitions",sheet:"COMPETITIONS_RESULTATS"}),readSheetRows({block:"acteurs",sheet:"ATHLETES"}),readSheetRows({block:"affiliations",sheet:"ATHLETE_AFFILIATIONS"}),readSheetRows({block:"acteurs",sheet:"COACHS"}),readSheetRows({block:"acteurs",sheet:"OFFICIELS"}),readSheetRows({block:"acteurs",sheet:"ARBITRES"}),readSheetRows({block:"acteurs",sheet:"MEDECINS"}),refs("TYPES_ACTEURS")])
 const map=(rs:SheetRow[],id:string)=>new Map(rs.map(r=>[clean(r[id]),label(r)])), dm=map(disciplines,"id_discipline"),cm=map(categories,"id_categorie_age"),xm=map(sexes,"id_sexe"),sm=map(seasonRefs,"id_saison"),csm=map(campaignStatuses,"id_statut_campagne"),ssm=map(selectionStatuses,"id_statut_selection"),esm=map(engagementStatuses,"id_statut_engagement"),pm=map(posts,"id_poste"),fm=map(functions,"id_fonction")
 const competitionMap=new Map(competitions.map(r=>[clean(r.id_competition),r])),eventMap=new Map(events.map(r=>[clean(r.id_epreuve_competition),r])),unitMap=new Map(units.map(r=>[clean(r.id_unite_competition),r])),matchMap=new Map(matches.map(r=>[clean(r.id_match),r]))
 const activations:Array<SheetRow&{id:string;saison:string}>=d.seasons.map(r=>({...r,id:clean(r.id_equipe_nationale_saison),saison:sm.get(clean(r.id_saison))||clean(r.id_saison)}))
 const campaigns:Array<SheetRow&{id:string;statut:string}>=d.campaigns.map(r=>({...r,id:clean(r.id_campagne_equipe_nationale),statut:csm.get(clean(r.id_statut_campagne))||clean(r.id_statut_campagne)}))
 const selections:Array<SheetRow&{id:string;poste:string;statut:string}>=d.selections.map(r=>({...r,id:clean(r.id_selection),poste:pm.get(clean(r.id_poste))||clean(r.id_poste),statut:ssm.get(clean(r.id_statut_selection))||clean(r.id_statut_selection)}))
 const staff:Array<SheetRow&{id:string;fonction:string}>=d.staff.map(r=>({...r,id:clean(r.id_affectation_staff),fonction:fm.get(clean(r.id_fonction))||clean(r.id_fonction)}))
 const engagements=d.engagements.map(r=>{const e=eventMap.get(clean(r.id_epreuve_competition)),c=competitionMap.get(clean(e?.id_competition));return{...r,id:clean(r.id_engagement_equipe_nationale),statut:esm.get(clean(r.id_statut_engagement))||clean(r.id_statut_engagement),epreuve:label(e),competition:label(c),id_competition:clean(c?.id_competition)}})
 const resultViews=results.flatMap(r=>{const match=matchMap.get(clean(r.id_match));if(!match)return[];const ua=unitMap.get(clean(match.id_unite_a)),ub=unitMap.get(clean(match.id_unite_b));return [{...r,...match,id:clean(r.id_resultat),unite_a:label(ua)||clean(match.id_unite_a),unite_b:label(ub)||clean(match.id_unite_b)}]})
 const teams=d.teams.map(r=>{const id=clean(r.id_equipe_nationale),acts=activations.filter(a=>clean(a.id_equipe_nationale)===id),campaignIds=new Set(campaigns.filter(c=>acts.some(a=>a.id===clean(c.id_equipe_nationale_saison))).map(c=>c.id));return{...r,id,nom:clean(r.nom_equipe_nationale),discipline:dm.get(clean(r.id_discipline))||clean(r.id_discipline),categorie:cm.get(clean(r.id_categorie_age))||clean(r.id_categorie_age),sexe:xm.get(clean(r.id_sexe))||clean(r.id_sexe),activations:acts,campaignCount:campaignIds.size,selectionCount:new Set(selections.filter(s=>campaignIds.has(clean(s.id_campagne_equipe_nationale))&&clean(s.id_statut_selection)==="SSL002").map(s=>clean(s.id_athlete))).size}})
 const actorOptions=[["TAC002",coaches,"id_coach"],["TAC003",officials,"id_officiel"],["TAC004",referees,"id_arbitre"],["TAC005",doctors,"id_medecin"]].flatMap(([type,rs,id])=>(rs as SheetRow[]).map(r=>({id:clean(r[id as string]),label:label(r),type}))).filter(x=>x.id)
 return {teams,activations,campaigns,selections:selections.map(s=>({...s,athlete:label(athletes.find(a=>clean(a.id_athlete)===clean(s.id_athlete)))})),staff:staff.map(s=>({...s,acteur:actorOptions.find(a=>a.id===clean(s.id_acteur)&&a.type===clean(s.id_type_acteur))?.label||clean(s.id_acteur)})),engagements,results:resultViews,references:{disciplines:disciplines.map(r=>({id:clean(r.id_discipline),label:label(r)})),categories:categories.map(r=>({id:clean(r.id_categorie_age),label:label(r)})),sexes:sexes.map(r=>({id:clean(r.id_sexe),label:label(r)})),seasons:seasonRefs.map(r=>({id:clean(r.id_saison),label:label(r)})),campaignStatuses:campaignStatuses.map(r=>({id:clean(r.id_statut_campagne),label:label(r)})),selectionStatuses:selectionStatuses.map(r=>({id:clean(r.id_statut_selection),label:label(r)})),engagementStatuses:engagementStatuses.map(r=>({id:clean(r.id_statut_engagement),label:label(r)})),posts:posts.map(r=>({id:clean(r.id_poste),label:label(r)})),functions:functions.map(r=>({id:clean(r.id_fonction),label:label(r)})),competitions:competitions.map(r=>({id:clean(r.id_competition),label:label(r)})),events:events.map(r=>({id:clean(r.id_epreuve_competition),competitionId:clean(r.id_competition),label:label(r)})),athletes:athletes.map(r=>({id:clean(r.id_athlete),label:label(r)})).filter(x=>x.id),athleteAffiliations:athleteAffiliations.map(r=>({id:clean(r.id_affiliation_athlete),athleteId:clean(r.id_athlete),label:clean(r.id_equipe)||clean(r.id_affiliation_athlete)})),actors:actorOptions,actorTypes:actorTypes.map(r=>({id:clean(r.id_type_acteur),label:label(r)}))}}
}

export async function mutateNationalTeam(action:string,input:unknown){
 const b=Object.fromEntries(Object.entries((input&&typeof input==="object"?input:{}) as Record<string,unknown>).map(([k,v])=>[k,clean(v)])),d=await loadCore(true),year=(b.id_saison.match(/\d{4}/)?.[0]||b.date_debut.slice(0,4)||String(new Date().getFullYear()))
 if(action==="team.create"){required(b,["nom_equipe_nationale","id_discipline","id_categorie_age","id_sexe"]);if(d.teams.some(r=>["id_discipline","id_categorie_age","id_sexe"].every(k=>clean(r[k])===b[k])))throw new NationalTeamError("DOUBLON","Cette équipe nationale existe déjà pour cette discipline, cette catégorie et ce sexe.",409);const id=generateNationalId("team","",d.teams.map(r=>clean(r.id_equipe_nationale)));return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.teams,idHeader:"id_equipe_nationale",id,values:b,mode:"create"})}
 if(action==="season.create"){required(b,["id_equipe_nationale","id_saison"]);if(!d.teams.some(r=>clean(r.id_equipe_nationale)===b.id_equipe_nationale))throw new NationalTeamError("RELATION_INVALIDE","Équipe nationale introuvable.");if(d.seasons.some(r=>clean(r.id_equipe_nationale)===b.id_equipe_nationale&&clean(r.id_saison)===b.id_saison))throw new NationalTeamError("DOUBLON","Cette équipe est déjà activée pour la saison sélectionnée.",409);const id=generateNationalId("season",year,d.seasons.map(r=>clean(r.id_equipe_nationale_saison)));return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.seasons,idHeader:"id_equipe_nationale_saison",id,values:{...b,statut:b.statut||"ACTIF"},mode:"create"})}
 if(action==="campaign.create"){required(b,["id_equipe_nationale_saison","nom_campagne","date_debut","date_fin"]);assertDates(b.date_debut,b.date_fin);const activation=d.seasons.find(r=>clean(r.id_equipe_nationale_saison)===b.id_equipe_nationale_saison);if(!activation)throw new NationalTeamError("RELATION_INVALIDE","Activation saisonnière introuvable.");const owner=sequenceFromId(clean(activation.id_equipe_nationale)),id=generateNationalId("campaign",year,d.campaigns.map(r=>clean(r.id_campagne_equipe_nationale)),owner);return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.campaigns,idHeader:"id_campagne_equipe_nationale",id,values:{...b,id_statut_campagne:b.id_statut_campagne||"SCA001"},mode:"create"})}
 if(action==="campaign.status"){const current=d.campaigns.find(r=>clean(r.id_campagne_equipe_nationale)===b.id);if(!current)throw new NationalTeamError("INTROUVABLE","Campagne introuvable.",404);assertCampaignTransition(clean(current.id_statut_campagne),b.id_statut_campagne);return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.campaigns,idHeader:"id_campagne_equipe_nationale",id:b.id,values:{id_statut_campagne:b.id_statut_campagne},mode:"update"})}
 if(action==="selection.create"){required(b,["id_campagne_equipe_nationale","id_athlete","id_affiliation_athlete","id_poste"]);const campaign=d.campaigns.find(r=>clean(r.id_campagne_equipe_nationale)===b.id_campagne_equipe_nationale);if(!campaign||["SCA003","SCA004"].includes(clean(campaign.id_statut_campagne)))throw new NationalTeamError("RELATION_INVALIDE","Cette campagne ne peut pas recevoir de sélection.");if(d.selections.some(r=>clean(r.id_campagne_equipe_nationale)===b.id_campagne_equipe_nationale&&clean(r.id_athlete)===b.id_athlete))throw new NationalTeamError("DOUBLON","Cet athlète est déjà enregistré dans cette campagne.",409);const aff=await readSheetRows({block:"affiliations",sheet:"ATHLETE_AFFILIATIONS",fresh:true});if(!aff.some(r=>clean(r.id_affiliation_athlete)===b.id_affiliation_athlete&&clean(r.id_athlete)===b.id_athlete))throw new NationalTeamError("AFFILIATION_INVALIDE","L’affiliation sélectionnée n’appartient pas à cet athlète.");const id=generateNationalId("selection",year,d.selections.map(r=>clean(r.id_selection)),sequenceFromId(clean(campaign.id_campagne_equipe_nationale)));return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.selections,idHeader:"id_selection",id,values:{...b,id_statut_selection:b.id_statut_selection||"SSL001",date_selection:b.date_selection||new Date().toISOString().slice(0,10)},mode:"create"})}
 if(action==="staff.create"){required(b,["id_equipe_nationale_saison","id_type_acteur","id_acteur","id_fonction","date_debut"]);assertDates(b.date_debut,b.date_fin);if(b.id_campagne_equipe_nationale&&!d.campaigns.some(r=>clean(r.id_campagne_equipe_nationale)===b.id_campagne_equipe_nationale&&clean(r.id_equipe_nationale_saison)===b.id_equipe_nationale_saison))throw new NationalTeamError("RELATION_INVALIDE","La campagne sélectionnée n’appartient pas à cette activation saisonnière.");const id=generateNationalId("staff",year,d.staff.map(r=>clean(r.id_affectation_staff)),sequenceFromId(b.id_campagne_equipe_nationale||b.id_equipe_nationale_saison));return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.staff,idHeader:"id_affectation_staff",id,values:{...b,statut:b.statut||"ACTIF"},mode:"create"})}
 if(action==="engagement.create"){required(b,["id_campagne_equipe_nationale","id_epreuve_competition","date_engagement"]);const campaign=d.campaigns.find(r=>clean(r.id_campagne_equipe_nationale)===b.id_campagne_equipe_nationale);if(!campaign||["SCA003","SCA004"].includes(clean(campaign.id_statut_campagne)))throw new NationalTeamError("RELATION_INVALIDE","Cette campagne ne peut pas recevoir d’engagement.");if(d.engagements.some(r=>clean(r.id_campagne_equipe_nationale)===b.id_campagne_equipe_nationale&&clean(r.id_epreuve_competition)===b.id_epreuve_competition))throw new NationalTeamError("DOUBLON","Un engagement existe déjà pour cette épreuve.",409);const id=generateNationalId("engagement",year,d.engagements.map(r=>clean(r.id_engagement_equipe_nationale)),sequenceFromId(b.id_campagne_equipe_nationale));const header=d.engagements[0]&&Object.prototype.hasOwnProperty.call(d.engagements[0],"id_statut_engagement")?"id_statut_engagement":"statut";return writeSheetRowByHeaders({block:"equipeNationale",sheet:sheets.engagements,idHeader:"id_engagement_equipe_nationale",id,values:{...b,[header]:b.id_statut_engagement||"SEG001",id_statut_engagement:""},mode:"create"})}
 throw new NationalTeamError("ACTION_INCONNUE","Action inconnue.",400)
}
