"use client"

import { useEffect,useState } from "react"
import { useParams } from "next/navigation"
import { DetailCard } from "@/components/dashboard/detail-card"
import { Header } from "@/components/dashboard/header"
import { nationalScoreLabel } from "@/lib/equipe-nationale-utils"
import type { ResultatEquipeNationale } from "@/lib/models"
export default function ResultatDetailPage(){const raw=useParams<{id:string}>().id;const id=decodeURIComponent(Array.isArray(raw)?raw[0]:raw);const[data,setData]=useState<ResultatEquipeNationale|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;(async()=>{try{const r=await fetch(`/api/equipe-nationale-resultats?id=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Lecture impossible");if(active)setData(j.resultat)}catch(e){if(active)setError(e instanceof Error?e.message:"Lecture impossible")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[id]);if(loading)return <><Header title="Résultat"/><div className="p-6 text-muted-foreground">Chargement...</div></>;if(error||!data)return <><Header title="Résultat"/><div className="p-6 text-destructive">{error||"Résultat introuvable."}</div></>;const overtime=data.prolongationA||data.prolongationB;return <div className="flex flex-col"><Header title={`${data.equipeNationaleNom} - ${data.nomAdversaire}`} subtitle={`${data.competitionNom} · ${data.dateMatch}`}/><div className="grid gap-6 p-6 lg:grid-cols-2"><DetailCard title="Match" fields={[{label:"ID résultat",value:data.id},{label:"Équipe nationale",value:data.equipeNationaleNom},{label:"Compétition",value:data.competitionNom},{label:"Date",value:data.dateMatch},{label:"Phase",value:data.phase},{label:"Adversaire",value:data.nomAdversaire},{label:"Pays adverse",value:data.paysAdversaire},{label:"Vainqueur",value:data.uniteVainqueurNom},{label:"Statut",value:data.statutMatch}]}/><DetailCard title="Score" fields={[{label:"Q1",value:`${data.qt1A||0} - ${data.qt1B||0}`},{label:"Q2",value:`${data.qt2A||0} - ${data.qt2B||0}`},{label:"Q3",value:`${data.qt3A||0} - ${data.qt3B||0}`},{label:"Q4",value:`${data.qt4A||0} - ${data.qt4B||0}`},...(overtime?[{label:"Prolongation",value:`${data.prolongationA||0} - ${data.prolongationB||0}`}]:[]),{label:"Score total",value:nationalScoreLabel(data)}]}/></div></div>}
