import { FIELD_WEIGHTS, clean, hasMeaningfulValue, validDate, valueFor } from "@/lib/data-quality/engine"
import type { CompletenessFieldRule, EntityCompletenessRule } from "@/lib/data-quality/types"

const { CRITICAL: C, IMPORTANT: I, COMPLEMENTARY: O } = FIELD_WEIGHTS
const field = (key: string, label: string, weight: 1|2|3, aliases?: string[]): CompletenessFieldRule => ({ key, label, weight, aliases })
const date = (key: string, label: string, weight: 1|2|3, aliases?: string[]): CompletenessFieldRule => ({ key, label, weight, aliases, code:"INVALID_DATE", isComplete:(row)=>validDate(valueFor(row, aliases?.length ? aliases : [key])) })
const optional = (rule: CompletenessFieldRule): CompletenessFieldRule => ({ ...rule, isApplicable: (row) => Object.prototype.hasOwnProperty.call(row, rule.key) && hasMeaningfulValue(row[rule.key]) })
const fk = (key:string,label:string,weight:1|2|3,reference:string,aliases?:string[]):CompletenessFieldRule => ({ key,label,weight,aliases,code:"UNKNOWN_FOREIGN_KEY",isComplete:(row,ctx)=>{const value=clean(valueFor(row,aliases?.length?aliases:[key]));return Boolean(value&&ctx.references[reference]?.has(value))} })
const period = (start="date_debut",end="date_fin"):CompletenessFieldRule => ({key:"periode",label:"Période",weight:I,code:"INVALID_PERIOD",severity:"WARNING",isApplicable:row=>hasMeaningfulValue(row[end]),isComplete:row=>validDate(row[start])&&validDate(row[end])&&clean(row[end])>=clean(row[start])})
const entity = (entityType:string,label:string,sheet:string,idAliases:string[],labelAliases:string[],fields:CompletenessFieldRule[]):EntityCompletenessRule => ({entityType,label,sheet,idAliases,labelAliases,fields})

const commonActor=(id:string,specific:CompletenessFieldRule[]=[])=>[field(id,"Identifiant",C),field("nom_complet","Nom complet",C),fk("id_sexe","Sexe",I,"SEXES"),date("date_naissance","Date de naissance",I,["date_naissance","date_de_naissance"]),field("nationalite","Nationalité",I),field("statut","Statut",C),...specific]

export const QUALITY_RULES = {
 structure:[
  entity("LIGUE","Ligue","LIGUES",["id_ligue"],["nom_ligue"],[field("id_ligue","Identifiant",C),field("nom_ligue","Nom",C),fk("id_province","Province",C,"PROVINCES"),field("statut","Statut",C)]),
  entity("ENTENTE","Entente","ENTENTES",["id_entente"],["nom_entente"],[field("id_entente","Identifiant",C),field("nom_entente","Nom",C),fk("id_ligue","Ligue parente",C,"LIGUES"),field("statut","Statut",C)]),
  entity("CLUB","Club","CLUBS",["id_club"],["nom_club"],[field("id_club","Identifiant",C),field("nom_club","Nom",C),fk("id_entente","Entente parente",C,"ENTENTES"),field("statut","Statut",C)]),
  entity("EQUIPE","Équipe","EQUIPES",["id_equipe"],["nom_equipe"],[field("id_equipe","Identifiant",C),fk("id_club","Club parent",C,"CLUBS"),fk("id_categorie_age","Catégorie",I,"CATEGORIES_AGE"),fk("id_sexe","Sexe",I,"SEXES"),field("statut","Statut",C)])],
 actors:[
  entity("ATHLETE","Athlète","ATHLETES",["id_athlete"],["nom_complet"],commonActor("id_athlete",[fk("id_categorie_age","Catégorie",I,"CATEGORIES_AGE")])),
  entity("COACH","Entraîneur","COACHS",["id_coach"],["nom_complet"],commonActor("id_coach",[field("id_niveau_coach","Niveau",I,["id_niveau_coach","id_niveau","id_niveau_coach_historique"]),optional(field("fonction","Fonction",I))])),
  entity("ARBITRE","Arbitre","ARBITRES",["id_arbitre"],["nom_complet"],commonActor("id_arbitre",[fk("id_grade_arbitre","Grade",I,"GRADES_ARBITRES")])),
  entity("MEDECIN","Médecin","MEDECINS",["id_medecin"],["nom_complet"],commonActor("id_medecin",[fk("id_specialite_sante","Spécialité",I,"SPECIALITES_MEDECINS",["id_specialite_sante","id_specialite"])])),
  entity("OFFICIEL","Officiel","OFFICIELS",["id_officiel"],["nom_complet"],commonActor("id_officiel",[optional(field("fonction","Fonction",I))])),
  entity("AUTRE","Autre acteur","AUTRES",["id_autre_acteur"],["nom_complet"],commonActor("id_autre_acteur",[fk("id_type_autre_acteur","Type d’acteur",I,"TYPES_AUTRES_ACTEURS",["id_type_autre_acteur","type_autre_acteur"])]))],
 licences:[
  entity("AFFILIATION_ATHLETE","Affiliation athlète","ATHLETE_AFFILIATIONS",["id_affiliation_athlete"],["id_affiliation_athlete"],[field("id_affiliation_athlete","Identifiant",C),fk("id_athlete","Athlète",C,"ATHLETES"),fk("id_equipe","Équipe",C,"EQUIPES"),date("date_debut","Date de début",I),fk("id_statut_affiliation","Statut",C,"STATUTS_AFFILIATION"),period()]),
  entity("AFFILIATION_COACH","Affiliation entraîneur","COACH_AFFILIATIONS",["id_affiliation_coach"],["id_affiliation_coach"],[field("id_affiliation_coach","Identifiant",C),fk("id_coach","Entraîneur",C,"COACHS"),fk("id_equipe","Équipe",C,"EQUIPES"),fk("id_fonction","Fonction",I,"FONCTIONS"),date("date_debut","Date de début",I),fk("id_statut_affiliation","Statut",C,"STATUTS_AFFILIATION"),period()]),
  entity("AFFILIATION_MEDECIN","Affiliation médecin","MEDECINS_AFFILIATIONS",["id_affiliation_medecin"],["id_affiliation_medecin"],[field("id_affiliation_medecin","Identifiant",C),fk("id_medecin","Médecin",C,"MEDECINS"),fk("id_equipe","Équipe",C,"EQUIPES"),date("date_debut","Date de début",I),fk("id_statut_affiliation","Statut",C,"STATUTS_AFFILIATION"),period()]),
  entity("AFFILIATION_OFFICIEL","Affiliation officiel","OFFICIELS_AFFILIATIONS",["id_affiliation_officiel"],["id_affiliation_officiel"],[field("id_affiliation_officiel","Identifiant",C),fk("id_officiel","Officiel",C,"OFFICIELS"),fk("id_fonction","Fonction",I,"FONCTIONS"),field("id_type_entite","Type d’entité",C),{key:"id_entite",label:"Entité",weight:C,code:"UNKNOWN_FOREIGN_KEY",isComplete:(row,ctx)=>{const id=clean(row.id_entite),type=clean(row.id_type_entite),sheet=type==="STR000"?"FEDERATION":type==="STR001"?"LIGUES":type==="STR002"?"ENTENTES":type==="STR003"?"CLUBS":"";return Boolean(sheet&&ctx.references[sheet]?.has(id))}},date("date_debut","Date de début",I),fk("id_statut_affiliation","Statut",C,"STATUTS_AFFILIATION"),period()]),
  entity("LICENCE_ATHLETE","Licence athlète","ATHLETE_LICENCES",["id_licence"],["numero_licence"],[field("id_licence","Identifiant",C),fk("id_athlete","Athlète",C,"ATHLETES"),fk("id_saison","Saison",C,"SAISON"),fk("id_affiliation_athlete","Affiliation",I,"ATHLETE_AFFILIATIONS"),field("numero_licence","Numéro officiel",C),date("date_delivrance","Date de délivrance",I),fk("id_statut_licence","Statut",C,"STATUT_LICENCE")]),
  entity("LICENCE_ACTEUR","Licence acteur","ACTEURS_LICENCES",["id_licence"],["numero_licence"],[field("id_licence","Identifiant",C),fk("id_type_acteur","Type d’acteur",C,"TYPES_ACTEURS"),{key:"id_acteur",label:"Acteur",weight:C,code:"UNKNOWN_FOREIGN_KEY",isComplete:(row,ctx)=>{const type=clean(row.id_type_acteur),sheet=type==="TAC002"?"COACHS":type==="TAC003"?"OFFICIELS":type==="TAC004"?"ARBITRES":type==="TAC005"?"MEDECINS":"";return Boolean(sheet&&ctx.references[sheet]?.has(clean(row.id_acteur)))}},fk("id_cycle_licence","Cycle",C,"CYCLES_LICENCES"),field("numero_licence","Numéro officiel",C),date("date_delivrance","Date de délivrance",I),date("date_debut_validite","Début de validité",I),date("date_fin_validite","Fin de validité",I),fk("id_statut_licence","Statut",C,"STATUT_LICENCE"),period("date_debut_validite","date_fin_validite")])],
 competitions:[
  entity("COMPETITION","Compétition","COMPETITIONS",["id_competition"],["nom_competition"],[field("id_competition","Identifiant",C),field("nom_competition","Nom",C),fk("id_saison","Saison",C,"SAISON"),date("date_debut","Date de début",I),date("date_fin","Date de fin",I),field("statut","Statut",C)]),
  entity("MATCH","Rencontre","COMPETITIONS_MATCHS",["id_match"],["id_match"],[field("id_match","Identifiant",C),fk("id_competition","Compétition",C,"COMPETITIONS"),field("id_unite_a","Participant A",I),field("id_unite_b","Participant B",I),date("date_match","Date",I),field("resultat","Résultat",C,["id_resultat","score_a"],),].map(x=>x.key==="resultat"?{...x,isApplicable:(r)=>/TERM|JOUE|CLOTUR/i.test(clean(r.statut_match))}:x))],
 nationalTeams:[
  entity("EQUIPE_NATIONALE","Équipe nationale","EQUIPES_NATIONALES",["id_equipe_nationale"],["nom_equipe_nationale"],[field("id_equipe_nationale","Identifiant",C),field("nom_equipe_nationale","Nom",C),fk("id_categorie_age","Catégorie",I,"CATEGORIES_AGE"),fk("id_sexe","Sexe",I,"SEXES"),field("statut","Statut",I)]),
  entity("ACTIVATION_NATIONALE","Activation saisonnière","EQUIPES_NATIONALES_SAISONS",["id_equipe_nationale_saison"],["id_equipe_nationale_saison"],[field("id_equipe_nationale_saison","Identifiant",C),fk("id_equipe_nationale","Équipe nationale",C,"EQUIPES_NATIONALES"),fk("id_saison","Saison",C,"SAISON"),field("statut","Statut",C)]),
  entity("CAMPAGNE_NATIONALE","Campagne","CAMPAGNES_EQUIPES_NATIONALES",["id_campagne_equipe_nationale"],["nom_campagne"],[field("id_campagne_equipe_nationale","Identifiant",C),fk("id_equipe_nationale_saison","Activation",C,"EQUIPES_NATIONALES_SAISONS"),field("nom_campagne","Nom",C),date("date_debut","Date de début",I),date("date_fin","Date de fin",I),field("id_statut_campagne","Statut",C)]),
  entity("SELECTION_NATIONALE","Sélection","SELECTIONS_ATHLETES",["id_selection"],["id_athlete"],[field("id_selection","Identifiant",C),fk("id_campagne_equipe_nationale","Campagne",C,"CAMPAGNES_EQUIPES_NATIONALES"),fk("id_athlete","Athlète",C,"ATHLETES"),field("id_poste","Poste",I),field("id_statut_selection","Statut",C)]),
  entity("STAFF_NATIONAL","Staff","AFFECTATIONS_STAFF",["id_affectation_staff"],["id_acteur"],[field("id_affectation_staff","Identifiant",C),field("id_acteur","Acteur",C),field("id_fonction","Fonction",I),fk("id_equipe_nationale_saison","Activation",C,"EQUIPES_NATIONALES_SAISONS"),date("date_debut","Date de début",I),field("statut","Statut",I)]),
  entity("ENGAGEMENT_NATIONAL","Engagement","ENGAGEMENTS_EQUIPE_NATIONALE",["id_engagement_equipe_nationale"],["id_engagement_equipe_nationale"],[field("id_engagement_equipe_nationale","Identifiant",C),fk("id_campagne_equipe_nationale","Campagne",C,"CAMPAGNES_EQUIPES_NATIONALES"),field("id_epreuve_competition","Épreuve",C),field("id_statut_engagement","Statut",C,["id_statut_engagement","statut"])])],
 activities:[
  entity("ACTIVITE","Activité","ACTIVITES",["id_activite"],["nom_activite"],[field("id_activite","Identifiant",C),field("id_type_activite","Type",C),field("nom_activite","Nom",C),date("date_debut","Date de début",C),optional(date("date_fin","Date de fin",I)),field("pays","Pays",I),field("ville","Ville",I),optional(field("lieu","Lieu",O)),field("statut","Statut",C),{key:"participants",label:"Participant ou entité associé",weight:I,code:"INCOMPLETE_RELATION",severity:"WARNING",isApplicable:r=>/TERMINE/i.test(clean(r.statut)),isComplete:(r,ctx)=>{const id=clean(r.id_activite);return(ctx.rows.ACTIVITES_PARTICIPANTS??[]).some(x=>clean(x.id_activite)===id)||(ctx.rows.ACTIVITES_ENTITES??[]).some(x=>clean(x.id_activite)===id)}}]),
  entity("ENTITE_ACTIVITE","Entité associée","ACTIVITES_ENTITES",["id_activite_entite"],["id_entite"],[field("id_activite_entite","Identifiant",C),fk("id_activite","Activité",C,"ACTIVITES"),field("id_entite","Entité",C),field("id_role_entite_activite","Rôle",I),field("statut_participation","Statut",I)]),
  entity("PARTICIPANT_ACTIVITE","Participant","ACTIVITES_PARTICIPANTS",["id_participation"],["id_acteur"],[field("id_participation","Identifiant",C),fk("id_activite","Activité",C,"ACTIVITES"),field("id_type_acteur","Type d’acteur",C),field("id_acteur","Acteur",C),field("role_participation","Rôle",I),field("statut_participation","Statut",I)])],
 documents:[
  entity("DOCUMENT","Document","DOCUMENTS",["id_document"],["titre_document"],[field("id_document","Identifiant",C),field("id_type_document","Type",C),field("titre_document","Titre",C),date("date_document","Date du document",I),field("statut","Statut",C),optional(field("numero_reference","Numéro de référence",I)),{key:"fichier",label:"Fichier",weight:C,code:"MISSING_FILE",isApplicable:r=>!/BROUILLON/i.test(clean(r.statut)),isComplete:(r,ctx)=>(ctx.rows.DOCUMENTS_FICHIERS??[]).some(x=>clean(x.id_document)===clean(r.id_document))}]),
  entity("FICHIER_DOCUMENT","Fichier","DOCUMENTS_FICHIERS",["id_fichier"],["nom_fichier"],[field("id_fichier","Identifiant",C),fk("id_document","Document",C,"DOCUMENTS"),field("nom_fichier","Nom",I),field("url_fichier","URL ou identifiant Drive",C,["url_fichier","id_fichier_drive"]),date("date_ajout","Date d’ajout",I)]),
  entity("RELATION_DOCUMENT","Relation","DOCUMENTS_RELATIONS",["id_relation_document"],["id_entite"],[field("id_relation_document","Identifiant",C),fk("id_document","Document",C,"DOCUMENTS"),field("id_type_entite","Type d’entité",C),field("id_entite","Entité",C),field("type_relation","Type de relation",I)])]
} satisfies Record<string,EntityCompletenessRule[]>

export const BLOCK_LABELS={structure:"Structure territoriale",actors:"Acteurs",licences:"Licences et affiliations",competitions:"Compétitions",nationalTeams:"Équipes nationales",activities:"Activités",documents:"Documents"} as const
