import type { SessionUser } from "@/lib/auth-session"
import { scopeFromSession, type AccessScope } from "@/lib/auth-scope"
import { evaluateBlock, clean } from "@/lib/data-quality/engine"
import { BLOCK_LABELS, QUALITY_RULES } from "@/lib/data-quality/rules"
import { DATA_QUALITY_BLOCKS, type DataQualityBlock, type DataQualityIssue, type DataQualitySummary } from "@/lib/data-quality/types"
import { dataQualityInvalidatedAt, invalidateDataQualityRevision } from "@/lib/data-quality/cache-version"
import { readSheetRowsBatch, type SheetBlock, type SheetRow } from "@/lib/google-sheets"

type Source={block:SheetBlock;sheets:string[]}
const sources:Source[]=[
 {block:"structure",sheets:["LIGUES","ENTENTES","CLUBS","EQUIPES"]},
 {block:"acteurs",sheets:["ATHLETES","COACHS","ARBITRES","MEDECINS","OFFICIELS","AUTRES"]},
 {block:"affiliations",sheets:["ATHLETE_AFFILIATIONS","COACH_AFFILIATIONS","MEDECINS_AFFILIATIONS","OFFICIELS_AFFILIATIONS"]},
 {block:"licences",sheets:["ATHLETE_LICENCES","ACTEURS_LICENCES"]},
 {block:"competitions",sheets:["COMPETITIONS","COMPETITIONS_EPREUVES","COMPETITIONS_PHASES","COMPETITIONS_GROUPES","COMPETITIONS_UNITES","COMPETITIONS_PHASES_UNITES","COMPETITIONS_PARTICIPANTS","COMPETITIONS_INTERVENANTS","COMPETITIONS_MATCHS","COMPETITIONS_RESULTATS","COMPETITIONS_CLASSEMENT","COMPETITIONS_DISTINCTIONS"]},
 {block:"equipeNationale",sheets:["EQUIPES_NATIONALES","EQUIPES_NATIONALES_SAISONS","CAMPAGNES_EQUIPES_NATIONALES","SELECTIONS_ATHLETES","AFFECTATIONS_STAFF","ENGAGEMENTS_EQUIPE_NATIONALE"]},
 {block:"activities",sheets:["ACTIVITES","ACTIVITES_ENTITES","ACTIVITES_PARTICIPANTS"]},
 {block:"documents",sheets:["DOCUMENTS","DOCUMENTS_FICHIERS","DOCUMENTS_RELATIONS"]},
 {block:"referentiel",sheets:["PROVINCES","FEDERATION","SAISON","SEXES","CATEGORIES_AGE","GRADES_ARBITRES","SPECIALITES_MEDECINS","TYPES_AUTRES_ACTEURS","FONCTIONS","STATUTS_AFFILIATION","STATUT_LICENCE","CYCLES_LICENCES","TYPES_ACTEURS","DISCIPLINES"]},
]
const sourceToQuality:Partial<Record<SheetBlock,DataQualityBlock[]>>={structure:["structure"],acteurs:["actors","licences","nationalTeams"],affiliations:["licences"],licences:["licences"],competitions:["competitions","nationalTeams"],equipeNationale:["nationalTeams"],activities:["activities"],documents:["documents"]}
type Cached={expiresAt:number;summary:DataQualitySummary;issues:DataQualityIssue[]}
const cache=new Map<string,Cached>(),pending=new Map<string,Promise<Cached>>()
const TTL=5*60_000
const keyFor=(scope:AccessScope,seasonId:string)=>`${scope.role}:${scope.role==="ligue"?scope.ligueId:scope.role==="entente"?scope.ententeId:"all"}:${seasonId||"current"}`

export function references(rows:Record<string,SheetRow[]>){const result:Record<string,Set<string>>={};for(const [sheet,items] of Object.entries(rows)){const ids=new Set<string>();for(const row of items)for(const [key,value] of Object.entries(row))if(key.startsWith("id_")&&value)ids.add(clean(value));if(sheet==="PROVINCES")for(const id of [...ids])if(/^PROV\d{3}$/.test(id))ids.add(`PRO${Number(id.slice(4)).toString().padStart(2,"0")}`);result[sheet]=ids}return result}
function scopeRows(rows:Record<string,SheetRow[]>,scope:AccessScope){if(scope.role==="federal")return rows;const ententes=rows.ENTENTES??[],clubs=rows.CLUBS??[],teams=rows.EQUIPES??[];const allowedEntentes=new Set(ententes.filter(r=>scope.role==="entente"?clean(r.id_entente)===scope.ententeId:clean(r.id_ligue)===scope.ligueId).map(r=>clean(r.id_entente)));const allowedClubs=new Set(clubs.filter(r=>allowedEntentes.has(clean(r.id_entente))).map(r=>clean(r.id_club)));const allowedTeams=new Set(teams.filter(r=>allowedClubs.has(clean(r.id_club))).map(r=>clean(r.id_equipe)));return{...rows,LIGUES:(rows.LIGUES??[]).filter(r=>scope.role==="ligue"?clean(r.id_ligue)===scope.ligueId:true),ENTENTES:ententes.filter(r=>allowedEntentes.has(clean(r.id_entente))),CLUBS:clubs.filter(r=>allowedClubs.has(clean(r.id_club))),EQUIPES:teams.filter(r=>allowedTeams.has(clean(r.id_equipe))),ATHLETE_AFFILIATIONS:(rows.ATHLETE_AFFILIATIONS??[]).filter(r=>allowedTeams.has(clean(r.id_equipe)))} }
function selectSeason(rows:Record<string,SheetRow[]>,requested:string){const seasons=rows.SAISON??[];if(requested&&seasons.some(r=>clean(r.id_saison)===requested))return requested;const year=String(new Date().getFullYear());return clean(seasons.find(r=>clean(r.nom_saison).includes(year)||clean(r.libelle).includes(year))?.id_saison)||clean(seasons[0]?.id_saison)}
function seasonFilter(rows:Record<string,SheetRow[]>,seasonId:string){if(!seasonId)return rows;const out={...rows};out.ATHLETE_LICENCES=(rows.ATHLETE_LICENCES??[]).filter(r=>clean(r.id_saison)===seasonId);out.COMPETITIONS=(rows.COMPETITIONS??[]).filter(r=>!clean(r.id_saison)||clean(r.id_saison)===seasonId);const competitionIds=new Set(out.COMPETITIONS.map(r=>clean(r.id_competition)));for(const sheet of ["COMPETITIONS_MATCHS","COMPETITIONS_RESULTATS","COMPETITIONS_PARTICIPANTS","COMPETITIONS_EPREUVES"])out[sheet]=(rows[sheet]??[]).filter(r=>competitionIds.has(clean(r.id_competition)));out.EQUIPES_NATIONALES_SAISONS=(rows.EQUIPES_NATIONALES_SAISONS??[]).filter(r=>clean(r.id_saison)===seasonId);const activationIds=new Set(out.EQUIPES_NATIONALES_SAISONS.map(r=>clean(r.id_equipe_nationale_saison)));out.CAMPAGNES_EQUIPES_NATIONALES=(rows.CAMPAGNES_EQUIPES_NATIONALES??[]).filter(r=>activationIds.has(clean(r.id_equipe_nationale_saison)));const campaignIds=new Set(out.CAMPAGNES_EQUIPES_NATIONALES.map(r=>clean(r.id_campagne_equipe_nationale)));for(const sheet of ["SELECTIONS_ATHLETES","ENGAGEMENTS_EQUIPE_NATIONALE"])out[sheet]=(rows[sheet]??[]).filter(r=>campaignIds.has(clean(r.id_campagne_equipe_nationale)));out.AFFECTATIONS_STAFF=(rows.AFFECTATIONS_STAFF??[]).filter(r=>activationIds.has(clean(r.id_equipe_nationale_saison)));return out}

async function calculate(user:SessionUser,requestedSeason="",fresh=false):Promise<Cached>{const started=Date.now(),settled=await Promise.allSettled(sources.map(source=>readSheetRowsBatch({...source,fresh})));let rows:Record<string,SheetRow[]>={},failed=new Set<DataQualityBlock>();settled.forEach((result,index)=>{const source=sources[index];if(result.status==="fulfilled")rows={...rows,...result.value};else{for(const block of sourceToQuality[source.block]??[])failed.add(block);console.warn(`[data-quality] source ${source.block} indisponible`,result.reason)}});const scope=scopeFromSession(user),seasonId=selectSeason(rows,requestedSeason);rows=seasonFilter(scopeRows(rows,scope),seasonId);const refs=references(rows),blocks=[],issues:DataQualityIssue[]=[];for(const block of DATA_QUALITY_BLOCKS){if(failed.has(block)){blocks.push({block,label:BLOCK_LABELS[block],score:null,status:"UNAVAILABLE" as const,records:0,complete:0,partial:0,critical:0,missingFields:0,issueCount:0,criticalIssues:0,unavailableReason:"Source momentanément indisponible"});continue}const result=evaluateBlock(block,BLOCK_LABELS[block],QUALITY_RULES[block],rows,{references:refs,rows,seasonId});blocks.push(result.summary);issues.push(...result.issues)}const totals=blocks.reduce((a,b)=>({records:a.records+b.records,complete:a.complete+b.complete,partial:a.partial+b.partial,critical:a.critical+b.critical,missingFields:a.missingFields+b.missingFields,issues:a.issues+b.issueCount,criticalIssues:a.criticalIssues+b.criticalIssues}),{records:0,complete:0,partial:0,critical:0,missingFields:0,issues:0,criticalIssues:0});const counts=new Map<string,number>();for(const issue of issues)counts.set(issue.code,(counts.get(issue.code)??0)+1);const labels:Record<string,string>={MISSING_REQUIRED_FIELD:"Champs obligatoires absents",INVALID_DATE:"Dates invalides",UNKNOWN_FOREIGN_KEY:"Relations inconnues",MISSING_FILE:"Fichiers manquants",INVALID_PERIOD:"Périodes invalides"};const summary:DataQualitySummary={calculatedAt:new Date().toISOString(),seasonId:seasonId||null,seasonLabel:clean((rows.SAISON??[]).find(r=>clean(r.id_saison)===seasonId)?.nom_saison)||seasonId||null,canRecalculate:scope.role==="federal",blocks,totals,topCategories:[...counts].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([code,count])=>({code,label:labels[code]||code,count}))};console.info(`[data-quality] calcul terminé en ${Date.now()-started}ms, ${totals.records} fiches, ${issues.length} anomalies`);return{expiresAt:Date.now()+TTL,summary,issues}}

export async function getDataQuality(user:SessionUser,seasonId="",fresh=false){const scope=scopeFromSession(user),key=keyFor(scope,seasonId);if(!fresh){const hit=cache.get(key);if(hit&&hit.expiresAt>Date.now()&&new Date(hit.summary.calculatedAt).getTime()>=dataQualityInvalidatedAt())return hit;const running=pending.get(key);if(running)return running}const task=calculate(user,seasonId,fresh).then(value=>{cache.set(key,value);return value}).finally(()=>pending.delete(key));pending.set(key,task);return task}
export function invalidateDataQuality(){cache.clear();invalidateDataQualityRevision()}
export function filterIssues(issues:DataQualityIssue[],query:{block?:string;severity?:string;code?:string;search?:string;page?:number;pageSize?:number}){const search=clean(query.search).toLowerCase();const filtered=issues.filter(i=>(!query.block||i.block===query.block)&&(!query.severity||i.severity===query.severity)&&(!query.code||i.code===query.code)&&(!search||`${i.entityId} ${i.entityLabel} ${i.fieldLabel} ${i.message}`.toLowerCase().includes(search)));const page=Math.max(1,query.page??1),pageSize=Math.min(100,Math.max(10,query.pageSize??25)),start=(page-1)*pageSize;return{items:filtered.slice(start,start+pageSize),total:filtered.length,page,pageSize,pages:Math.ceil(filtered.length/pageSize)}}
