"use client"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Eye, Pencil, Plus, RefreshCw, Users } from "lucide-react"
import { Header } from "@/components/dashboard/header"
import { DataTable, type Column } from "@/components/dashboard/data-table"
import { LicenceEditor, type LicenceView } from "@/components/dashboard/licence-editor"
import { StatusBadge } from "@/components/dashboard/status-badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { formatDisplayDate } from "@/lib/date-format"

type Option={id:string;label:string;clubId?:string;clubLabel?:string;ententeId?:string;ententeLabel?:string;ligueId?:string;ligueLabel?:string}
type Summary={total:number;hommes:number;femmes:number;actives:number;nonActives:number}
type TeamSummary=Option&Summary
const emptyRefs={seasons:[] as Option[],statuses:[] as Option[],teams:[] as Option[],athletes:[] as Option[]},emptySummary:Summary={total:0,hommes:0,femmes:0,actives:0,nonActives:0}
export default function LicencesPage(){const[licences,setLicences]=useState<LicenceView[]>([]),[references,setReferences]=useState(emptyRefs),[summary,setSummary]=useState(emptySummary),[teams,setTeams]=useState<TeamSummary[]>([]),[seasonId,setSeasonId]=useState(""),[ligueId,setLigueId]=useState("all"),[ententeId,setEntenteId]=useState("all"),[clubId,setClubId]=useState("all"),[teamId,setTeamId]=useState("all"),[sexId,setSexId]=useState("all"),[statusId,setStatusId]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[federal,setFederal]=useState(false),[editorOpen,setEditorOpen]=useState(false),[editing,setEditing]=useState<LicenceView|null>(null),[editorMode,setEditorMode]=useState<"ATHLETE"|"EQUIPE">("ATHLETE"),[editorReadOnly,setEditorReadOnly]=useState(false)
 const load=useCallback(async(selectedSeason="")=>{setLoading(true);setError("");try{const q=selectedSeason?`?saison=${encodeURIComponent(selectedSeason)}`:"",r=await fetch(`/api/licences${q}`,{cache:"no-store"}),p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Lecture impossible.");setLicences(p.licences||[]);setReferences(p.references||emptyRefs);setSummary(p.summary||emptySummary);setTeams(p.teamSummary||[]);if(!selectedSeason&&!seasonId){const target=(p.references?.seasons||[]).find((x:Option)=>x.label===String(new Date().getFullYear()))?.id||p.references?.seasons?.[0]?.id||"";setSeasonId(target)}}catch(e){setError(e instanceof Error?e.message:"Lecture impossible.")}finally{setLoading(false)}},[seasonId])
 useEffect(()=>{void load();void fetch("/api/auth/me").then(r=>r.json()).then(p=>setFederal(p?.user?.role==="federal"))},[]) // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(seasonId)void load(seasonId)},[seasonId]) // eslint-disable-line react-hooks/exhaustive-deps
 const ligues=useMemo(()=>[...new Map(references.teams.filter(x=>x.ligueId).map(x=>[x.ligueId!,x.ligueLabel||x.ligueId!])).entries()],[references]),ententes=useMemo(()=>[...new Map(references.teams.filter(x=>(ligueId==="all"||x.ligueId===ligueId)&&x.ententeId).map(x=>[x.ententeId!,x.ententeLabel||x.ententeId!])).entries()],[references,ligueId]),clubs=useMemo(()=>[...new Map(references.teams.filter(x=>(ententeId==="all"||x.ententeId===ententeId)&&x.clubId).map(x=>[x.clubId!,x.clubLabel||x.clubId!])).entries()],[references,ententeId]),teamOptions=references.teams.filter(x=>(clubId==="all"||x.clubId===clubId)&&(ententeId==="all"||x.ententeId===ententeId)&&(ligueId==="all"||x.ligueId===ligueId))
 const visible=licences.filter(x=>(ligueId==="all"||x.ligueId===ligueId)&&(ententeId==="all"||x.ententeId===ententeId)&&(clubId==="all"||x.clubId===clubId)&&(teamId==="all"||x.equipeId===teamId)&&(sexId==="all"||x.sexId===sexId)&&(statusId==="all"||x.statusId===statusId)),visibleTeams=teams.filter(x=>(ligueId==="all"||x.ligueId===ligueId)&&(ententeId==="all"||x.ententeId===ententeId)&&(clubId==="all"||x.clubId===clubId)&&(teamId==="all"||x.id===teamId))
 const columns:Column<LicenceView>[]=[{key:"numero",header:"N° licence",className:"font-mono"},{key:"athleteNom",header:"Athlète",className:"font-medium"},{key:"sexe",header:"Sexe"},{key:"saison",header:"Saison"},{key:"clubNom",header:"Club"},{key:"dateDelivrance",header:"Délivrée le"},{key:"statut",header:"Statut",render:x=><StatusBadge status={x.statut}/>}]
 const openEditor=(mode:"ATHLETE"|"EQUIPE",item:LicenceView|null=null,readOnly=false)=>{setEditorMode(mode);setEditing(item);setEditorReadOnly(readOnly);setEditorOpen(true)},picker=(value:string,onChange:(v:string)=>void,label:string,options:[string,string][])=><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full sm:w-48"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="all">{label}</SelectItem>{options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>
 return <div className="flex flex-col"><Header title="Licences des athlètes" subtitle="Licences enregistrées par saison et par structure territoriale"/><main className="space-y-6 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><Select value={seasonId} onValueChange={setSeasonId}><SelectTrigger className="w-44"><SelectValue placeholder="Saison"/></SelectTrigger><SelectContent>{references.seasons.map(x=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select>{federal?<div className="flex flex-wrap gap-2"><Button onClick={()=>openEditor("ATHLETE")}><Plus/>Enregistrer une licence</Button><Button variant="outline" onClick={()=>openEditor("EQUIPE")}><Users/>Renouveler par équipe</Button></div>:null}</div>
 {error?<Card className="border-destructive/40"><CardContent className="py-8 text-center"><p className="text-destructive">{error}</p><Button variant="outline" className="mt-3" onClick={()=>void load(seasonId)}><RefreshCw/>Réessayer</Button></CardContent></Card>:<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total des licences",summary.total],["Athlètes masculins",summary.hommes],["Athlètes féminins",summary.femmes],["Licences actives",summary.actives],["Expirées / clôturées",summary.nonActives]].map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>)}</div>
 <Card><CardHeader><CardTitle>Synthèse territoriale</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{picker(ligueId,v=>{setLigueId(v);setEntenteId("all");setClubId("all");setTeamId("all")},"Toutes les ligues",ligues)}{picker(ententeId,v=>{setEntenteId(v);setClubId("all");setTeamId("all")},"Toutes les ententes",ententes)}{picker(clubId,v=>{setClubId(v);setTeamId("all")},"Tous les clubs",clubs)}{picker(teamId,setTeamId,"Toutes les équipes",teamOptions.map(x=>[x.id,x.label]))}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left">{["Équipe","Club","Total","Hommes","Femmes","Actives","Non actives","Action"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{visibleTeams.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-medium">{x.label}</td><td className="p-3">{x.clubLabel}</td><td className="p-3">{x.total}</td><td className="p-3">{x.hommes}</td><td className="p-3">{x.femmes}</td><td className="p-3">{x.actives}</td><td className="p-3">{x.nonActives}</td><td className="p-3"><Button size="sm" variant="ghost" onClick={()=>setTeamId(x.id)}>Voir les licenciés</Button></td></tr>)}</tbody></table></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Licences enregistrées</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{picker(sexId,setSexId,"Tous les sexes",[["SEX001","Masculin"],["SEX002","Féminin"]])}{picker(statusId,setStatusId,"Tous les statuts",references.statuses.map(x=>[x.id,x.label]))}</div>{loading?<p className="py-8 text-center text-muted-foreground">Chargement…</p>:<DataTable data={visible} columns={columns} idKey="__key" searchPlaceholder="Nom, identifiant ou numéro de licence…" renderActions={item=><div className="flex gap-1"><Button size="icon-sm" variant="ghost" title="Voir" onClick={()=>openEditor("ATHLETE",item,true)}><Eye/></Button>{federal?<Button size="icon-sm" variant="ghost" title="Modifier" onClick={()=>openEditor("ATHLETE",item)}><Pencil/></Button>:null}</div>} renderMobileCard={item=><Card><CardContent className="space-y-2 p-4"><div className="flex justify-between"><strong>{item.athleteNom}</strong><StatusBadge status={item.statut}/></div><p className="text-sm">{item.numero} · {item.equipeNom}</p><p className="text-xs text-muted-foreground">{item.ligueNom} · {formatDisplayDate(item.dateDelivrance)}</p></CardContent></Card>}/>}</CardContent></Card></>}</main><LicenceEditor open={editorOpen} onOpenChange={setEditorOpen} references={references} editing={editing} initialMode={editorMode} readOnly={editorReadOnly} onSaved={()=>void load(seasonId)}/></div>}
